
package view;

import controller.ManajemenDashbord;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Anjar
 */
public class AbsensiGuru extends javax.swing.JFrame {

    /**
     * Creates new form AbsensiGuru
     */
     DefaultTableModel tabeldasbor;
     
      public void loadTblDashboard() throws SQLException{
       ManajemenDashbord mdtl = new ManajemenDashbord();
        mdtl.loadData(tabeldasbor);
        
       // mdtl.loadDataDasborSiang(tabeldasbor);
         try {
            int guru = mdtl.getTotalGuru();
            Dasbor_jumlah_guru.setText(String.valueOf(guru));
            int kehadiran = mdtl.getJumlahGuru();      
            Dasbor_persentase_kehadiran.setText(String.valueOf((kehadiran))+" Data");
            
             
        } catch (SQLException ex) {
            Logger.getLogger(AbsensiGuru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public AbsensiGuru() {
        initComponents();
        
    
        
            ImageIcon icon = new ImageIcon("src/images/absensi.png");
        setIconImage(icon.getImage());
        tabeldasbor = new DefaultTableModel();
        
        //menambahkan TableModel ke Tabel
        tbdasbor.setModel(tabeldasbor);        
    
        tabeldasbor.addColumn("TANGGAL");
        tabeldasbor.addColumn("NIP");
        tabeldasbor.addColumn("NAMA GURU");
        tabeldasbor.addColumn("JABATAN");
        tabeldasbor.addColumn("ABSEN MASUK");
        tabeldasbor.addColumn("ABSEN KELUAR");
        
           //+++++++++Agar memulai aplikasi berada di tengah layar
    
        Dimension ss = Toolkit.getDefaultToolkit ().getScreenSize ();
        Dimension frameSize = new Dimension ( 1100, 700 );
        this.setBounds ( ss.width / 2 - frameSize.width / 2, 
                  ss.height / 2 - frameSize.height / 2,
                  frameSize.width, frameSize.height );
                  
           label_tanggal3.setText(new SimpleDateFormat("YYYY-MM-dd").format(new java.util.Date()));
        
        jam();
          
    }
    private void jam() {
     Timer tt = new Timer();
     tt.scheduleAtFixedRate(new TimerTask() {
         
         @Override
         public void run() {

            //  tampil_jam3.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
             label_jam3.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));

         }
     }, 0, 1000);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_laporan_guru = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbdasbor = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Dasbor_persentase_kehadiran = new javax.swing.JLabel();
        Dasbor_jumlah_guru = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        label_tanggal3 = new javax.swing.JLabel();
        label_jam3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        p_laporan_guru.setBackground(new java.awt.Color(102, 204, 255));
        p_laporan_guru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p_laporan_guru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbdasbor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbdasbor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdasborMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbdasbor);

        p_laporan_guru.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 700, 380));

        jLabel15.setBackground(new java.awt.Color(204, 204, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data Presensi ");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel15.setOpaque(true);
        p_laporan_guru.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 270, 30));

        Dasbor_persentase_kehadiran.setBackground(new java.awt.Color(255, 102, 102));
        Dasbor_persentase_kehadiran.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Dasbor_persentase_kehadiran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dasbor_persentase_kehadiran.setText("-");
        Dasbor_persentase_kehadiran.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Dasbor_persentase_kehadiran.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dasbor_persentase_kehadiran.setOpaque(true);
        p_laporan_guru.add(Dasbor_persentase_kehadiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 270, -1));

        Dasbor_jumlah_guru.setBackground(new java.awt.Color(255, 102, 102));
        Dasbor_jumlah_guru.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Dasbor_jumlah_guru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dasbor_jumlah_guru.setText("-");
        Dasbor_jumlah_guru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Dasbor_jumlah_guru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dasbor_jumlah_guru.setOpaque(true);
        p_laporan_guru.add(Dasbor_jumlah_guru, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 270, -1));

        jLabel64.setBackground(new java.awt.Color(51, 255, 51));
        jLabel64.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Jumlah Presensi");
        jLabel64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel64.setOpaque(true);
        p_laporan_guru.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 270, 20));

        jLabel65.setBackground(new java.awt.Color(204, 204, 0));
        jLabel65.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Jumlah Guru");
        jLabel65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel65.setOpaque(true);
        p_laporan_guru.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 270, 30));

        jLabel66.setBackground(new java.awt.Color(102, 204, 255));
        jLabel66.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel66.setOpaque(true);
        p_laporan_guru.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 290, 380));

        jLabel83.setText("logo smk");
        p_laporan_guru.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 270, 190));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("Cek Data Hari Ini");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        p_laporan_guru.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("PRESENSI GURU SMK PGRI 28 JAKARTA");
        p_laporan_guru.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        label_tanggal3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_tanggal3.setText("tgl");
        label_tanggal3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                label_tanggal3FocusGained(evt);
            }
        });
        p_laporan_guru.add(label_tanggal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 30));

        label_jam3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_jam3.setText("lbl jam");
        p_laporan_guru.add(label_jam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/full-time.png"))); // NOI18N
        p_laporan_guru.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/date.png"))); // NOI18N
        p_laporan_guru.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, -1, 20));

        getContentPane().add(p_laporan_guru, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(283, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-menu-25.png"))); // NOI18N
        jMenu1.setText("MENU ABSENSI");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sunrise-25.png"))); // NOI18N
        jMenuItem1.setText("ABSENSI MASUK");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sun-25.png"))); // NOI18N
        jMenuItem2.setText("ABSENSI KELUAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-exit-sign-16.png"))); // NOI18N
        jMenu3.setText("KELUAR APLIKASI");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jMenuItem4.setText("Keluar Aplikasi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1074, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbdasborMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdasborMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbdasborMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            loadTblDashboard();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AbsensiGuru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void label_tanggal3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label_tanggal3FocusGained
        // TODO add your handling code here:
        TableRowSorter<TableModel>sorter= new TableRowSorter<TableModel>(((DefaultTableModel)tbdasbor.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(label_jam3.getText()));
        tbdasbor.setRowSorter(sorter);
    }//GEN-LAST:event_label_tanggal3FocusGained

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
      AbsensiMasuk masuk = new AbsensiMasuk();
      this.dispose();
      masuk.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AbsensiKeluar k = new AbsensiKeluar();
      this.dispose();
      k.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        //  JOptionPane.showMessageDialog(null,"Keluar Aplikasi","Pesan",JOptionPane.YES_NO_OPTION);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsensiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsensiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsensiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsensiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbsensiGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dasbor_jumlah_guru;
    private javax.swing.JLabel Dasbor_persentase_kehadiran;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label_jam3;
    private javax.swing.JLabel label_tanggal3;
    private javax.swing.JPanel p_laporan_guru;
    private javax.swing.JTable tbdasbor;
    // End of variables declaration//GEN-END:variables
}
