
package view;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import controller.SubmitPresensi;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import model.Hadir;

/**
 *
 * @author Anjar
 */
public class AbsensiMasuk extends javax.swing.JFrame implements Runnable, ThreadFactory  {

    /**
     * Creates new form AbsensiMasuk
     */
          private WebcamPanel panel = null;
    private Webcam webcam = null;

    private static final long serialVersionUID = 6441489157408381878L;
    private Executor executor = Executors.newSingleThreadExecutor(this);
    
      private List<Hadir> ambil   = new ArrayList<Hadir>(); 
    public AbsensiMasuk() {
        initComponents();
        initWebcam_masuk();
         ImageIcon icon = new ImageIcon("src/images/absensi.png");
        setIconImage(icon.getImage());

           //+++++++++Agar memulai aplikasi berada di tengah layar
    
        Dimension ss = Toolkit.getDefaultToolkit ().getScreenSize ();
        Dimension frameSize = new Dimension ( 1100, 700 );
        this.setBounds ( ss.width / 2 - frameSize.width / 2, 
                  ss.height / 2 - frameSize.height / 2,
                  frameSize.width, frameSize.height );
                  
        
        //Informasi hari, tanggal
                 
          label_tanggal.setText(new SimpleDateFormat("dd-MMMM-YYYY").format(new java.util.Date()));
          txtNip.requestFocus();

        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        label_error_message = new javax.swing.JLabel();
        label_jamkerja = new javax.swing.JLabel();
        tampil_jam = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        foto_guru = new javax.swing.JLabel();
        label_NipGuru = new javax.swing.JLabel();
        label_NamaGuru = new javax.swing.JLabel();
        label_JabatanGuru = new javax.swing.JLabel();
        lbtugas = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbversi = new javax.swing.JLabel();
        txtid_jam = new javax.swing.JLabel();
        webcam_masuk = new javax.swing.JPanel();
        panel_webcam = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(102, 204, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_error_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_error_message.setText("silahkan");
        mainPanel.add(label_error_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 310, -1));

        label_jamkerja.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_jamkerja.setForeground(new java.awt.Color(255, 255, 255));
        label_jamkerja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_jamkerja.setText("Jam Masuk");
        label_jamkerja.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(label_jamkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 250, 20));

        tampil_jam.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tampil_jam.setText("03 : 00 :00");
        mainPanel.add(tampil_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, -1));

        txtNip.setFont(new java.awt.Font("Lucida Gr", 0, 24)); // NOI18N
        txtNip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNip.setToolTipText("");
        txtNip.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNip.setInheritsPopupMenu(true);
        txtNip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNipFocusGained(evt);
            }
        });
        txtNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNipActionPerformed(evt);
            }
        });
        txtNip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNipKeyReleased(evt);
            }
        });
        mainPanel.add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 290, 50));

        jLabel1.setFont(new java.awt.Font("Lucida G", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukan NIP"));
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 310, 80));

        foto_guru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto_guru.setToolTipText("");
        foto_guru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(foto_guru, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 250, 220));

        label_NipGuru.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_NipGuru.setForeground(new java.awt.Color(255, 255, 255));
        label_NipGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_NipGuru.setText("Nip");
        label_NipGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(label_NipGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 250, 20));

        label_NamaGuru.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_NamaGuru.setForeground(new java.awt.Color(255, 255, 255));
        label_NamaGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_NamaGuru.setText("Nama Guru");
        label_NamaGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(label_NamaGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 250, 20));

        label_JabatanGuru.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_JabatanGuru.setForeground(new java.awt.Color(255, 255, 255));
        label_JabatanGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_JabatanGuru.setText("Jabatan");
        label_JabatanGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(label_JabatanGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 250, 20));

        lbtugas.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lbtugas.setForeground(new java.awt.Color(255, 255, 255));
        lbtugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtugas.setText("Tugas Tambahan");
        lbtugas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(lbtugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 250, 20));

        label_tanggal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_tanggal.setText("Sabtu 10 Januari 2014");
        mainPanel.add(label_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Absensi Masuk");
        mainPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(102, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Pastikan waktu keluar dan masuk anda\nsesuai jadwal yang ditentukan\n2. Arahkan Pointer ke Nip Yang Akan di Scan\n3. Dekatkan barcode Kartu Tanda Guru anda\nke scanner ( Jika memakai Scanner )\n4. Tunggu sampai NIP terbaca dan tertulis\ninformasi tentang anda di layar\n5. Anda Berhasil Melakukan Absen");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tata Cara Presensi Guru "));
        jScrollPane1.setViewportView(jTextArea1);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 270, 190));

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 290, 390));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setOpaque(true);
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 330, 410));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/full-time.png"))); // NOI18N
        mainPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/date.png"))); // NOI18N
        mainPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        lbversi.setFont(new java.awt.Font("Lucida G", 3, 12)); // NOI18N
        lbversi.setForeground(new java.awt.Color(255, 255, 255));
        lbversi.setText("Absensi Guru V .1 .0");
        mainPanel.add(lbversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 120, 20));

        txtid_jam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtid_jam.setForeground(new java.awt.Color(255, 255, 255));
        txtid_jam.setText("1");
        mainPanel.add(txtid_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 10, 20));

        webcam_masuk.setBackground(new java.awt.Color(0, 102, 102));
        webcam_masuk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        webcam_masuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_webcam.setBackground(new java.awt.Color(250, 250, 250));
        panel_webcam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_webcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        webcam_masuk.add(panel_webcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 330));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tombol_next.png"))); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        webcam_masuk.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tombol_stop.png"))); // NOI18N
        jButton2.setText("stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        webcam_masuk.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, 50));

        mainPanel.add(webcam_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 390, 410));

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(283, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-menu-25.png"))); // NOI18N
        jMenu1.setText("MENU ABSENSI");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sun-25.png"))); // NOI18N
        jMenuItem2.setText("ABSENSI KELUAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/graphic-design.png"))); // NOI18N
        jMenu2.setText("HOME");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-attendance-25.png"))); // NOI18N
        jMenuItem3.setText("DATA ABSEN GURU");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1090, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        initWebcam_stop();
AbsensiKeluar keluar = new AbsensiKeluar();
        
this.dispose();
keluar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        initWebcam_stop();
AbsensiGuru data = new AbsensiGuru();

this.dispose();
data.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtNipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNipFocusGained

    }//GEN-LAST:event_txtNipFocusGained

    private void txtNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNipActionPerformed

    private void txtNipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNipKeyReleased
        run();
        txtNip.setText("");

    }//GEN-LAST:event_txtNipKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        initWebcam_stop();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        initWebcam_masuk();
        txtNip.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsensiMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
            new AbsensiMasuk().setVisible(true);
          }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foto_guru;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_JabatanGuru;
    private javax.swing.JLabel label_NamaGuru;
    private javax.swing.JLabel label_NipGuru;
    private javax.swing.JLabel label_error_message;
    private javax.swing.JLabel label_jamkerja;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JLabel lbtugas;
    private javax.swing.JLabel lbversi;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel_webcam;
    private javax.swing.JLabel tampil_jam;
    private javax.swing.JTextField txtNip;
    private javax.swing.JLabel txtid_jam;
    private javax.swing.JPanel webcam_masuk;
    // End of variables declaration//GEN-END:variables
private void jam() {
     Timer tt = new Timer();
     tt.scheduleAtFixedRate(new TimerTask() {
         
         @Override
         public void run() {
             tampil_jam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
  
         }
     }, 0, 1000);
 }

//WEBCAM

    private void initWebcam_masuk() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        panel_webcam.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 240));

        executor.execute(this);
    }
    
    private void initWebcam_stop() {
//        Dimension size = WebcamRes.olution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.close();
    }
    
  @Override
   public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;
        
            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
           
            try {
                result = new MultiFormatReader().decode(bitmap);
               
            } catch (NotFoundException e) {
                //No result...
            }
            //Hadir guru = new Hadir();
            if (result != null) {
           String nip =result.getText(); 
            
              txtNip.setText(nip);
                
               masuk_kerja();  
            }
           
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r);
        t.setDaemon(true);
        return t;
    }
    
    public void masuk_kerja(){
            String nip;
           String id_jam;
            boolean status_guru, status_hadir;
            nip = txtNip.getText();
            id_jam= txtid_jam.getText();
            Hadir guru = new Hadir();
            guru.setNip(nip);
            guru.setId_Jam(id_jam);
            if(!"".equals(nip)){
            
                SubmitPresensi kehadiran = new SubmitPresensi();
                try{
                    //cek apakah pegawai ada di tabel pegawai
                    status_guru = kehadiran.cek_guru(guru);
                    if(status_guru == true){
                        //cek dia harusnya masuk jam berapa
                        Date jam = new Date();

                        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                       String jam_sekarang = format.format(jam.getTime());

                        ambil = kehadiran.ambil(guru);
                       
                        String data[] = new String[6];
                        for(Hadir h : ambil){
                            data[0] = h.getNip_guru();
                            data[1] = h.getNama();
                            data[2] = h.getJabatan();
                            data[3] = h.getId_Jam();
                            data[4] = h.getFoto();
                            data[5] = h.getTugas();
                        }
                     
                        Time waktu[] = new Time[1];
                        for(Hadir h : ambil){
                            waktu[0] = h.getMasukStart();
                        }

                        Time longjam = Time.valueOf(jam_sekarang);

                        long lj = longjam.getTime();
                        long mm = waktu[0].getTime();
                        //cek apakah pegawai tsb sudah absen masuk atau belum
                        status_hadir = kehadiran.cek_kehadiran(guru);
                        if(status_hadir == true){
                            
                            if(mm < lj ){
                                
                                kehadiran.masuk(guru.getNip());
                                label_NipGuru.setText(data[0]);
                                label_NamaGuru.setText(data[1]);
                                label_JabatanGuru.setText(data[2]);
                               foto_guru.setIcon(new ImageIcon(new ImageIcon(data[4]).getImage().getScaledInstance(foto_guru.getWidth(), foto_guru.getHeight(), Image.SCALE_SMOOTH)));
                             
                                foto_guru.setText("");
                                lbtugas.setText(data[5]);
                                
                                label_error_message.setText("Masuk Berhasil");
                                label_jamkerja.setText("In : " +jam_sekarang);
//                               
                                txtNip.setText("");
                                txtNip.requestFocus();
                            }
                            else{

                                label_error_message.setText("Anda tidak diperkenankan");
                            }
                        }
                    }
                                         
                }catch(SQLException ex){
                    label_error_message.setText("Kesalahan Database");
                }
            }
            else
            {
                label_error_message.setText("Masukan NIP");
            }
            
            txtNip.requestFocus();
             txtNip.setText("");
        }

}
