/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author User
 */
public class About extends javax.swing.JInternalFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_about = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();

        setTitle("About");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-about-16.png"))); // NOI18N

        p_about.setBackground(new java.awt.Color(255, 255, 255));
        p_about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setText("Tentang Software");
        p_about.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, 242, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 0));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel29.setText("Admin Presensi Guru Versi 1.0");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 11, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("           \n\n             Absensi guru ini di buat agar kami belajar lebih dalam\n             mata kuliah pemrograman berbasis objek. Bahasa pemrograman\n             yang kami perdalam adalah bahasa pemrograman JAVA. \n\n              Versi Java yang kami gunakan adalah 8.2 dengan bantuan\n              Netbeans IDE 8.2 sebagai Software Development-nya, XAMPP\n              sebagai bantuan Web Server & Mysql Sebagai Databasenya.\n              \n               Aplikasi Absensi Guru ini mendukung untuk penggunaan Scan\n               Barcode Maupun QR-Code, Dan Aplikasi Ini Menggunakan \n               Metode Client Dan Server.\n               Dimana Administrator Sebagai Servernya Dan Absensi Sebagai\n               Client.\n               Semoga aplikasi Absensi Guru ini dapat bermanfaat bagi \n               Penggunanya.\n\n\n                                                                   Develop By Team KKP Unindra 2021");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setFocusable(false);
        jScrollPane9.setViewportView(jTextArea1);

        jPanel13.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 86, 502, 352));

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/Untitled.png"))); // NOI18N
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Dashboard Utama Admin");
        jPanel13.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unindra2.png"))); // NOI18N
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 90, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pgrikecil.jpg"))); // NOI18N
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 80, 80));

        jTabbedPane1.addTab("Tentang Aplikasi", new javax.swing.ImageIcon(getClass().getResource("/icon/graphic-design.png")), jPanel13); // NOI18N

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setTabSize(5);
        jTextArea2.setText("\t\n\tNama    : Muhammad Anjar\n\tNPM      : 201743501456\n\t   \n\t\n\tNama    : Nurul Hady \n\tNPM      : 201743501313\n\t\n\n\tNama    : Rizki Maulana\n\tNPM      : 201743501364\n\t\n\t\n\tNama    : Maulana sakti\n\tNPM      : 20174350\n\t\n");
        jScrollPane10.setViewportView(jTextArea2);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setTabSize(5);
        jTextArea8.setText("\t\n\tNama    : Arief Abdul Karim\n\tNPM      : 201743501304\n\t\n\t\n\tNama    : Sugi Asep\n\tNPM     : 201743501311\n\t\n\n\tNama    : Rangga Heryanto\n\tNPM     : 201743501417\n\t\n\t\n\tNama    : Kiki A\n\tNPM      : 20174350\n\t\n");
        jScrollPane16.setViewportView(jTextArea8);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("S1 TEKNIK INFORMATIKA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UNIVERSITAS INDRAPRASTA PGRI (UNINDRA)");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane16))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pengembang Aplikasi", new javax.swing.ImageIcon(getClass().getResource("/icon/customers.png")), jPanel14); // NOI18N

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(51, 51, 51));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/CIMOL.png"))); // NOI18N
        jLabel39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, 160));

        jLabel41.setBackground(new java.awt.Color(51, 51, 51));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/ANJAR.jpg"))); // NOI18N
        jLabel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 160));

        jLabel56.setBackground(new java.awt.Color(51, 51, 51));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/hady.jpg"))); // NOI18N
        jLabel56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel56.setOpaque(true);
        jPanel15.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 150, 160));

        jLabel57.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Muhammad Anjar");
        jPanel15.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Nurul Hady");
        jPanel15.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Rizki Maulana");
        jPanel15.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));
        jPanel15.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 0, -1, 520));

        jLabel51.setBackground(new java.awt.Color(51, 51, 51));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/LICIN.png"))); // NOI18N
        jLabel51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 160, 160));

        jLabel60.setText("jLabel51");
        jLabel60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, 160));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Arief Abdul Karim");
        jPanel15.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel62.setBackground(new java.awt.Color(51, 51, 51));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/UGI.png"))); // NOI18N
        jLabel62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 160, 160));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Maulana Sakti");
        jPanel15.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, -1, 20));
        jPanel15.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 0, -1, 520));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Sugi Asep");
        jPanel15.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jLabel42.setBackground(new java.awt.Color(51, 51, 51));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/CAPLANG.jpg"))); // NOI18N
        jLabel42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 180, 160));

        jLabel43.setBackground(new java.awt.Color(51, 51, 51));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhotoPengembang/KIKI.png"))); // NOI18N
        jLabel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 170, 160));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Rangga Heryanto");
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Kiki Aristiani");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jTabbedPane1.addTab("Photo Profile Pengembang Aplikasi", new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-student-male-25.png")), jPanel15); // NOI18N

        p_about.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 47, 960, 480));

        jLabel105.setBackground(new java.awt.Color(204, 204, 255));
        jLabel105.setOpaque(true);
        p_about.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1030, 570));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel52.setText("@ Copyright Team KKP Unindra 2021");
        p_about.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(p_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(p_about, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JPanel p_about;
    // End of variables declaration//GEN-END:variables
}
