/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import SessionLogin.UserID;
import controller.KoneksiDB;
import controller.ManajemenAbsensi;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelAbsensi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormAbsenGuru extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAbsenGuru1
     */
   //variabel menu popup
     public String nip_guru, nama_guru,jabatan_guru;
    String tanggal_mulai;
   String tanggal_selesai;
      String tanggal_ajuan;


      private Connection conn = new KoneksiDB().getKoneksi();
     //Tabel Absen Guru
        DefaultTableModel tabelabsen;
        public void loadTblAbsen() throws SQLException{
        ManajemenAbsensi matl = new ManajemenAbsensi();
        matl.loadDataAbsen(tabelabsen);
    }
    public FormAbsenGuru() throws SQLException {
        initComponents();
        
         cbthn.setText(new SimpleDateFormat("YYYY").format(new java.util.Date()));
         
          tabelabsen = new DefaultTableModel();
        //menambahkan TableModel ke Tabel
        tbabsen.setModel(tabelabsen);
        
        tabelabsen.addColumn("NO");
        tabelabsen.addColumn("TANGGAL");
        tabelabsen.addColumn("NIP");
        tabelabsen.addColumn("NAMA");
        tabelabsen.addColumn("JABATAN");
        tabelabsen.addColumn("TANGGAL MULAI");
        tabelabsen.addColumn("TANGGAL SELSESAI");
        tabelabsen.addColumn("JUMLAH HARI");
        tabelabsen.addColumn("KETERANGAN");
         tabelabsen.addColumn("TAHUN");    
        tabelabsen.addColumn("FILE PHOTO");
         tabelabsen.addColumn("PATH");
        absentengah();
        headerabsen();
 
       
       txtkode.setEnabled(false);
        txtanip.setEnabled(false);
        txtatanggal.setEnabled(false);
        lbtotalhari.setEnabled(false);
        jdtglmulai.setEnabled(false);
        jdtglselesai.setEnabled(false);
        txtaketerangan.setEnabled(false);
//        radaizin.setEnabled(false);
//        radacuti.setEnabled(false);
         cbthn.setEnabled(false);
        
        loadTblAbsen();
      
        String KD = UserID.getUserLogin();
        txtidadm7.setText(KD);
        String NM = UserID.getNamaLogin();
        txtnamaadm7.setText(NM);
    }
    public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = KoneksiDB.getKoneksi();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
           JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
           JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    //pemanggilan menu popup
 public void itemTerpilih(){
          ListGuru lp = new ListGuru();
          lp.guru=this;
          txtanip.setText(nip_guru);   
          lblnamaguru.setText(nama_guru);  
          lbjabatanguru.setText(jabatan_guru);  
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_izin = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtnamaadm7 = new javax.swing.JLabel();
        txtidadm7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        img_foto_absen = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtanip = new javax.swing.JTextField();
        txtatanggal = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        txtaketerangan = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btnAbsen_ubah = new javax.swing.JButton();
        btnAbsen_hapus = new javax.swing.JButton();
        btnAbsen_simpan = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jdtglmulai = new com.toedter.calendar.JDateChooser();
        jdtglselesai = new com.toedter.calendar.JDateChooser();
        jLabel37 = new javax.swing.JLabel();
        lbjabatanguru = new javax.swing.JLabel();
        txtcariabsenguru = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbabsen = new javax.swing.JTable();
        btnAbsen_tambah1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblnamaguru = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        btnAbsen_hapus1 = new javax.swing.JButton();
        lbtotalhari = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAbsen_hapus2 = new javax.swing.JButton();
        lbphoto = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        cbthn = new javax.swing.JTextField();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-attendance-25.png"))); // NOI18N

        p_izin.setBackground(new java.awt.Color(255, 255, 255));
        p_izin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnamaadm7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnamaadm7.setForeground(new java.awt.Color(255, 255, 255));
        txtnamaadm7.setText("jLabel55");
        jPanel7.add(txtnamaadm7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 140, 20));

        txtidadm7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidadm7.setForeground(new java.awt.Color(255, 255, 255));
        txtidadm7.setText("jLabel23");
        jPanel7.add(txtidadm7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 80, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("PHOTO PROFILE");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 20));

        img_foto_absen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_foto_absen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(img_foto_absen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 190));

        txtkode.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtkode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtkode.setOpaque(false);
        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        jPanel7.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, 30));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setText("NAMA");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 30));

        txtanip.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtanip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtanip.setOpaque(false);
        txtanip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanipActionPerformed(evt);
            }
        });
        jPanel7.add(txtanip, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 180, 30));

        txtatanggal.setDateFormatString("dd MMM, yyyy");
        txtatanggal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtatanggal.setOpaque(false);
        txtatanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtatanggalPropertyChange(evt);
            }
        });
        jPanel7.add(txtatanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 200, 30));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setText("JUMLAH HARI");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 90, 30));

        txtaketerangan.setColumns(3);
        txtaketerangan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtaketerangan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtaketerangan.setOpaque(false);
        txtaketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaketeranganActionPerformed(evt);
            }
        });
        jPanel7.add(txtaketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 200, 30));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("  KETERANGAN");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 100, 30));

        btnAbsen_ubah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_ubah.setForeground(new java.awt.Color(255, 51, 0));
        btnAbsen_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-file-25.png"))); // NOI18N
        btnAbsen_ubah.setText("Ubah");
        btnAbsen_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_ubahActionPerformed(evt);
            }
        });
        jPanel7.add(btnAbsen_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 100, 30));

        btnAbsen_hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_hapus.setForeground(new java.awt.Color(255, 51, 0));
        btnAbsen_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-trash-25.png"))); // NOI18N
        btnAbsen_hapus.setText("Hapus");
        btnAbsen_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_hapusActionPerformed(evt);
            }
        });
        jPanel7.add(btnAbsen_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 100, 30));

        btnAbsen_simpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_simpan.setForeground(new java.awt.Color(255, 51, 0));
        btnAbsen_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-save-25.png"))); // NOI18N
        btnAbsen_simpan.setText("Simpan");
        btnAbsen_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_simpanActionPerformed(evt);
            }
        });
        jPanel7.add(btnAbsen_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 110, 30));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel28.setText("FORM CUTI GURU");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 108, -1, -1));
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 108, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setText("NIP");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 30));

        jdtglmulai.setDateFormatString("dd MMM, yyyy");
        jdtglmulai.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jdtglmulai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdtglmulaiPropertyChange(evt);
            }
        });
        jPanel7.add(jdtglmulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 200, 30));

        jdtglselesai.setDateFormatString("dd MMM, yyyy");
        jdtglselesai.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jdtglselesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdtglselesaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jdtglselesaiMouseReleased(evt);
            }
        });
        jdtglselesai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdtglselesaiFocusLost(evt);
            }
        });
        jdtglselesai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdtglselesaiPropertyChange(evt);
            }
        });
        jdtglselesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdtglselesaiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdtglselesaiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdtglselesaiKeyTyped(evt);
            }
        });
        jPanel7.add(jdtglselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 200, 30));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setText("JABATAN");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 30));

        lbjabatanguru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbjabatanguru.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(lbjabatanguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 180, 30));

        txtcariabsenguru.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtcariabsenguru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariabsenguruKeyReleased(evt);
            }
        });
        jPanel7.add(txtcariabsenguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 200, 30));

        tbabsen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbabsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "          TANGGAL", "                 NIP", "               NAMA", "              JABATAN", "        KETERANGAN", "         TAHUN      ", "FOTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbabsen.setGridColor(new java.awt.Color(0, 0, 0));
        tbabsen.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbabsen.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbabsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbabsenMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbabsen);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 970, 120));

        btnAbsen_tambah1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_tambah1.setForeground(new java.awt.Color(255, 51, 0));
        btnAbsen_tambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-25.png"))); // NOI18N
        btnAbsen_tambah1.setText("Tambah");
        btnAbsen_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_tambah1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnAbsen_tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 110, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 350, 220));

        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 290, 220));

        lblnamaguru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblnamaguru.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(lblnamaguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 154, 180, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-more-25.png"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-more-25.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 40, 30));

        btnAbsen_hapus1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_hapus1.setForeground(new java.awt.Color(255, 51, 0));
        btnAbsen_hapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancel-25.png"))); // NOI18N
        btnAbsen_hapus1.setText("Batal");
        btnAbsen_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_hapus1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnAbsen_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 100, 30));

        lbtotalhari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbtotalhari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbtotalhari.setText("N/A");
        lbtotalhari.setBorder(null);
        lbtotalhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtotalhariActionPerformed(evt);
            }
        });
        lbtotalhari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbtotalhariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbtotalhariFocusLost(evt);
            }
        });
        lbtotalhari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbtotalhariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbtotalhariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbtotalhariKeyTyped(evt);
            }
        });
        jPanel7.add(lbtotalhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 190, 80, 30));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel41.setText("Tahun Ajaran");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 80, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pen.png"))); // NOI18N
        jButton1.setText("Proses Hari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 120, 30));

        btnAbsen_hapus2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_hapus2.setForeground(new java.awt.Color(255, 51, 0));
        btnAbsen_hapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-trash-25.png"))); // NOI18N
        btnAbsen_hapus2.setText("Hapus Per Tahun");
        btnAbsen_hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_hapus2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnAbsen_hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 170, 30));

        lbphoto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbphoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lbphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-microsoft-excel-25.png"))); // NOI18N
        jButton7.setText("Export ( Excel 2003 )");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 180, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setText("TGL SELESAI");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 90, 23));

        jLabel96.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel96.setText("NO RECORD");
        jPanel7.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, 20));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setText(" TGL MULAI");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 80, 23));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel38.setText("TGL PENGAJUAN");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 120, 23));

        jLabel48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 990, 180));

        jLabel98.setBackground(new java.awt.Color(255, 255, 255));
        jLabel98.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel98.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel98.setOpaque(true);
        jPanel7.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 990, 280));

        cbthn.setEditable(false);
        cbthn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(cbthn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 80, 30));

        javax.swing.GroupLayout p_izinLayout = new javax.swing.GroupLayout(p_izin);
        p_izin.setLayout(p_izinLayout);
        p_izinLayout.setHorizontalGroup(
            p_izinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        p_izinLayout.setVerticalGroup(
            p_izinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_izinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(p_izin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(p_izin, javax.swing.GroupLayout.PREFERRED_SIZE, 545, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void txtanipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanipActionPerformed

    private void txtaketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaketeranganActionPerformed

    private void btnAbsen_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_ubahActionPerformed
        // TODO add your handling code here:

        int i = tbabsen.getSelectedRow();
        if(i== -1 | "".equals(txtkode.getText())){
            JOptionPane.showMessageDialog(null, "Tidak ada data absen yang dipilih");

            txtkode.setText("");

        }
        txtkode.setEnabled(false);
        txtanip.setEnabled(true);
        cbthn.setEnabled(true);
        txtatanggal.setEnabled(true);
        jdtglmulai.setEnabled(true);
        jdtglselesai.setEnabled(true);
        lbtotalhari.setEnabled(true);
//        radaizin.setEnabled(true);
//        radacuti.setEnabled(true);

        txtaketerangan.setEnabled(true);
    }//GEN-LAST:event_btnAbsen_ubahActionPerformed

    private void btnAbsen_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_hapusActionPerformed
        // TODO add your handling code here:

        int row = tbabsen.getSelectedRow();
        if(row!= -1){
            String cell = tbabsen.getModel().getValueAt(row, 0).toString();
            String nomer = tbabsen.getValueAt(row, 0).toString();

            String sql = "DELETE FROM tbabsen where kode='"+nomer+"'";
            String resetno="ALTER TABLE tbabsen DROP `kode`;";
            String consecutivenumber="ALTER TABLE tbabsen ADD `kode` INT(11) NOT NULL AUTO_INCREMENT FIRST ,ADD KEY(`kode`);";

            if (JOptionPane.showConfirmDialog(null, "HAPUS DATA INI..??"
                ,"KONFIRMASI",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE)== JOptionPane.OK_OPTION) {

            try {
                conn.createStatement().execute(sql);
                conn.createStatement().execute(resetno);
                conn.createStatement().execute(consecutivenumber);

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                loadTblAbsen();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Klik Salah Satu Tabel");
        }
        }
        /*
        int i = tbabsen.getSelectedRow();
        if(i== -1){
            return;
        }

        // int no = Integer.parseInt(txtkode.getText());
        ModelAbsensi moda = new ModelAbsensi();
        moda.setKode(txtkode.getText());

        int konfirmasiHapus = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin akan menghapus data absensi tersebut?", "Hapus Pegawai", JOptionPane.YES_NO_OPTION);
        if(konfirmasiHapus == JOptionPane.YES_OPTION){
            try{
                ManajemenAbsensi mana = new ManajemenAbsensi();
                mana.hapusGuru(moda);
                JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus", "Berhasil Menghapus Data",JOptionPane.INFORMATION_MESSAGE);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan menghapus data","Kesalahan Menghapus Data",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try {
                    loadTblAbsen();

                    txtkode.setText("");
                    txtanip.setEnabled(false);
                    txtanip.setText("");

                    txtatanggal.setEnabled(false);
                    txtatanggal.setDate(null);

                    radaizin.setEnabled(false);
                    radacuti.setEnabled(false);
                    radaizin.setSelected(false);
                    radacuti.setSelected(false);

                    txtaketerangan.setEnabled(true);
                    txtaketerangan.setText("");

                } catch (SQLException ex) {
                    Logger.getLogger(Administrator
                        .class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }*/
    }//GEN-LAST:event_btnAbsen_hapusActionPerformed

    private void btnAbsen_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_simpanActionPerformed
        // TODO add your handling code here:
        String absen_kode = txtkode.getText();
        String absen_nip = txtanip.getText();
        String admin = txtidadm7.getText();
        Date absen_tanggal = txtatanggal.getDate();
         Date absen_tanggal_mulai = jdtglmulai.getDate();
          Date absen_tanggal_selesai = jdtglselesai.getDate();
          String hari = lbtotalhari.getText();
String tahun = cbthn.getText().toString();
//        String absen_izin = "";
//
//        if(jenis_absen.getSelection().equals(radacuti.getModel())){
//            absen_izin = "Cuti";
//        }
//        else if(jenis_absen.getSelection().equals(radaizin.getModel())){
//            absen_izin = "Izin";
//        }else{
//            JOptionPane.showMessageDialog(null, "Harap isi semua field");
//        }

        String absen_keterangan = txtaketerangan.getText();

        if( "".equals(absen_nip) | txtatanggal.getDate()== null|jdtglmulai.getDate()== null  |jdtglselesai.getDate()== null  | "".equals(absen_keterangan) ){
            JOptionPane.showMessageDialog(null, "Harap isi semua field");
        }else{

            int confirmSimpan = JOptionPane.showConfirmDialog(null,"Apakah anda data tersebut sudah benar?","Mengimput data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){

                ModelAbsensi moda = new ModelAbsensi();
                moda.setKode(absen_kode);
                moda.setNip(absen_nip);
//                moda.setAbsen(absen_izin);
                moda.setTanggal(absen_tanggal);
                moda.setTgl_mulai(absen_tanggal_mulai);
                moda.setTgl_selesai(absen_tanggal_selesai);
                moda.setTotal(hari);
                moda.setKeterangan(absen_keterangan);
                moda.setId_adm(admin);
                moda.setTahun(tahun);
                try{
                    ManajemenAbsensi mana = new ManajemenAbsensi();
                    if(mana.cekGuru(moda) == true){
                        if(mana.cekDuplikasi(moda) == true){
                            int ubahData = JOptionPane.showConfirmDialog(this,
                                "Data tersebut sudah ada di database. \n"
                                + "apakah anda yakin mau merubahnya?", "Ubah data absen",
                                JOptionPane.YES_NO_CANCEL_OPTION);
                            if(ubahData == JOptionPane.YES_OPTION){
                                try{
                                    moda.setKode(txtkode.getText());
                                    mana.ubahAbsen(moda);
                                    JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Data berhasil diubah",JOptionPane.INFORMATION_MESSAGE);
                                }catch(SQLException ex){
                                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan mengubah data","Kesalahan Mengubah data",JOptionPane.ERROR_MESSAGE);
                                    Logger.getLogger(FormAbsenGuru.class.getName()).log(Level.SEVERE, null, ex);
                                }finally{
                                    loadTblAbsen();

                                }

                            }else if(ubahData == JOptionPane.NO_OPTION){

                                txtanip.setEnabled(false);

                                txtatanggal.setEnabled(false);
                                txtatanggal.setDate(null);
                                 jdtglmulai.setEnabled(false);
                                jdtglmulai.setDate(null);
                                 jdtglselesai.setEnabled(false);
                                jdtglselesai.setDate(null);
//                                radaizin.setEnabled(false);
//                                radacuti.setEnabled(false);
                                cbthn.setEnabled(false);
                                txtaketerangan.setEnabled(false);
                            }

                        }else{
                            try{
                                mana.tambahAbsen(moda);
                                JOptionPane.showMessageDialog(null, "Data berhasil ditambah", "Data berhasil ditambah",JOptionPane.INFORMATION_MESSAGE);
                            }catch(SQLException ex){
                                JOptionPane.showMessageDialog(null, "Terjadi kesalahan menambahkan data","Kesalahan Menambah Data",JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(FormAbsenGuru.class.getName()).log(Level.SEVERE, null, ex);
                            }finally{
                                loadTblAbsen();

                                txtkode.setText("");
                                txtkode.setEnabled(false);
                                txtanip.setEnabled(false);
                                txtanip.setText("");
                                txtanip.requestFocus();

                                txtatanggal.setEnabled(false);
                                txtatanggal.setDate(null);
                                jdtglmulai.setEnabled(false);
                                jdtglmulai.setDate(null);
                                jdtglselesai.setEnabled(false);
                                jdtglselesai.setDate(null);

//                                radaizin.setEnabled(false);
//                                radacuti.setEnabled(false);
//                                radaizin.setSelected(false);
//                                radacuti.setSelected(false);

                                txtaketerangan.setEnabled(false);
                                txtaketerangan.setText("");
                                lbtotalhari.setEnabled(false);
                                lbtotalhari.setText("");
                                 lbjabatanguru.setEnabled(false);
                                lbjabatanguru.setText("");
                                lbjabatanguru.setEnabled(false);
                                lblnamaguru.setText("");
                               
                            }
                        }

                    }else{
                        JOptionPane.showMessageDialog(null, "Guru dengan nip "+moda.getNip()+" tidak ditemukan","Tidak ditemukan",JOptionPane.ERROR_MESSAGE);
                    }
                }catch(SQLException ex){
                    Logger.getLogger(FormAbsenGuru.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnAbsen_simpanActionPerformed

    private void txtcariabsenguruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariabsenguruKeyReleased
        // TODO add your handling code here:
        TableRowSorter<TableModel>sorter= new TableRowSorter<TableModel>(((DefaultTableModel)tbabsen.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(txtcariabsenguru.getText()));
        tbabsen.setRowSorter(sorter);
    }//GEN-LAST:event_txtcariabsenguruKeyReleased

    private void tbabsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbabsenMouseClicked
        // TODO add your handling code here:

        //ubah keadaan field-field menjadi tidak berfungsi
        txtanip.setEnabled(false);
        txtatanggal.setEnabled(false);
         jdtglmulai.setEnabled(false);
          jdtglselesai.setEnabled(false);
           lbtotalhari.setEnabled(false);
//        radaizin.setEnabled(false);
//        radacuti.setEnabled(false);
        txtaketerangan.setEnabled(false);

        //cek apakah salah satu baris sudah diklik
        int i = tbabsen.getSelectedRow();
        if(i== -1){
            //tidak melakukan apa-apa
            return;
        }

        /*
        mengambil isi dari tabel yang di klik, lalu menampilkannya
        * di field-field
        */

        String No_rec_absen = (tabelabsen.getValueAt(i, 0)).toString();
        txtkode.setText(No_rec_absen);

        Date tanggal = (Date)tabelabsen.getValueAt(i, 1);
        txtatanggal.setDate(tanggal);

        String nip = (String) tabelabsen.getValueAt(i, 2);
        txtanip.setText(nip);
        String nama = (String) tabelabsen.getValueAt(i, 3);
        lblnamaguru.setText(nama);
        String jb = (String) tabelabsen.getValueAt(i, 4);
        lbjabatanguru.setText(jb);

//        String cuti_izin = (String) tabelabsen.getValueAt(i, 5);
//        if("Cuti".equals(cuti_izin)){
//            radacuti.setSelected(true);
//        }else{
//            radaizin.setSelected(true);
//        }
        
        Date mulai = (Date)tabelabsen.getValueAt(i, 5);
        jdtglmulai.setDate(mulai);
        
         Date selesai = (Date)tabelabsen.getValueAt(i, 6);
        jdtglselesai.setDate(selesai);
        
        String hari = (String) tabelabsen.getValueAt(i, 7);
        lbtotalhari.setText(hari);
        
        String keterangan = (String) tabelabsen.getValueAt(i, 8);
        txtaketerangan.setText(keterangan);

        String foto = (String) tabelabsen.getValueAt(i, 10);
         lbphoto.setText(foto);
        String files = (String) tabelabsen.getValueAt(i, 11);
        img_foto_absen.setIcon(new ImageIcon(new ImageIcon(files).getImage().getScaledInstance(img_foto_absen.getWidth(), img_foto_absen.getHeight(), Image.SCALE_SMOOTH)));//("D:/PICT/"+foto)));
       
         String tahun = (String) tabelabsen.getValueAt(i, 9);
        cbthn.setText(tahun);
// img_foto_absen.setIcon((new javax.swing.ImageIcon("../kkp_foto/"+foto)));
    }//GEN-LAST:event_tbabsenMouseClicked

    private void btnAbsen_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_tambah1ActionPerformed
        // TODO add your handling code here:  txtkode.setText("");
        
        txtkode.setText("");
        txtkode.setEnabled(false);
        txtkode.setText("");
        txtkode.requestFocus();

        txtanip.setText("");
        txtanip.setEnabled(true);
        txtanip.setText("");

        txtatanggal.setEnabled(true);
        txtatanggal.setDate(null);
        jdtglmulai.setEnabled(true);
        jdtglmulai.setDate(null);
        jdtglselesai.setEnabled(true);
        jdtglselesai.setDate(null);
         lbtotalhari.setText("");
        lbtotalhari.setEnabled(true);
        lbtotalhari.setText("");

        txtaketerangan.setText("");
        txtaketerangan.setEnabled(true);
        txtaketerangan.setText("");

    
//        radaizin.setEnabled(true);
//        radacuti.setEnabled(true);
          
        cbthn.setEnabled(true);
    }//GEN-LAST:event_btnAbsen_tambah1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        ListGuru lp = new ListGuru();
        lp.guru = this;
        //this.getParent().add(lp);

        lp.setVisible(true);
        lp.setResizable(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnAbsen_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_hapus1ActionPerformed
        // TODO add your handling code here:
        txtkode.setText("");
        txtanip.setText("");
        txtatanggal.setDate(null);
         jdtglmulai.setDate(null);
          jdtglselesai.setDate(null);
        txtaketerangan.setText("");
        lbtotalhari.setText("");

        lbtotalhari.setEnabled(false);
                               
                                 lbjabatanguru.setEnabled(false);
                                lbjabatanguru.setText("");
                                lbjabatanguru.setEnabled(false);
                                lblnamaguru.setText("");
    }//GEN-LAST:event_btnAbsen_hapus1ActionPerformed

    private void txtatanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtatanggalPropertyChange
        // TODO add your handling code here:
        
        if (txtatanggal.getDate() !=null) {
            SimpleDateFormat format = new SimpleDateFormat("dd MMMM yyyy");
               tanggal_ajuan = format.format(txtatanggal.getDate());
            
        }
    }//GEN-LAST:event_txtatanggalPropertyChange

    private void jdtglmulaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdtglmulaiPropertyChange
        // TODO add your handling code here:
          
        if (jdtglmulai.getDate() !=null) {
            SimpleDateFormat format = new SimpleDateFormat("dd MMM,yyyy");
               tanggal_mulai = format.format(jdtglmulai.getDate());
            
        }
    }//GEN-LAST:event_jdtglmulaiPropertyChange

    private void jdtglselesaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdtglselesaiPropertyChange
        // TODO add your handling code here:
         if (jdtglselesai.getDate() !=null) {
            SimpleDateFormat format = new SimpleDateFormat("dd MMM,yyyy");
               tanggal_selesai = format.format(jdtglselesai.getDate());
            
        }
    }//GEN-LAST:event_jdtglselesaiPropertyChange

    private void jdtglselesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdtglselesaiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdtglselesaiKeyPressed

    private void jdtglselesaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtglselesaiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdtglselesaiMousePressed

    private void jdtglselesaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdtglselesaiKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jdtglselesaiKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\   try {
            try{
            DateFormat format = new SimpleDateFormat("dd MMM,yyyy");
            Date tgl_mulai = format.parse(tanggal_mulai);
             Date tgl_selesai = format.parse(tanggal_selesai);
             long mulai1 = tgl_mulai.getTime();
            long selesai1 = tgl_selesai.getTime();
            long diff = selesai1-mulai1;
            long lama= diff/(24*60*60*1000);
            lbtotalhari.setText(Long.toString(lama)+" Hari");
            
        } catch (Exception e) {
            System.out.println(""+e.getMessage());
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbtotalhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtotalhariActionPerformed
        // TODO add your handling code here:
       
            
    }//GEN-LAST:event_lbtotalhariActionPerformed

    private void jdtglselesaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdtglselesaiKeyTyped
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jdtglselesaiKeyTyped

    private void lbtotalhariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbtotalhariFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbtotalhariFocusGained

    private void lbtotalhariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbtotalhariKeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lbtotalhariKeyReleased

    private void jdtglselesaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtglselesaiMouseReleased
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jdtglselesaiMouseReleased

    private void lbtotalhariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbtotalhariKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lbtotalhariKeyPressed

    private void lbtotalhariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbtotalhariFocusLost
        // TODO add your handling code here:\
    
    }//GEN-LAST:event_lbtotalhariFocusLost

    private void jdtglselesaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdtglselesaiFocusLost
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jdtglselesaiFocusLost

    private void lbtotalhariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbtotalhariKeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_lbtotalhariKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showSaveDialog(FormAbsenGuru.this);
        if (option== JFileChooser.APPROVE_OPTION) {
            String filename = fc.getSelectedFile().getName();
            String path = fc.getSelectedFile().getParentFile().getPath();
            int len = filename.length();
            String ext="";
            String file = "";
            if (len > 4) {
                ext = filename.substring(len-4, len);

            }
            if (ext.equals(".xls")) {
                file = path + "\\" + filename+ "";

            }else{
                file = path + "\\" + filename+ ".xls";
            }
            toExcel(tbabsen, new File(file));
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnAbsen_hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_hapus2ActionPerformed
        // TODO add your handling code here:
          int row = tbabsen.getSelectedRow();
        if(row!= -1){
            String cell = tbabsen.getModel().getValueAt(row, 0).toString();
            String tahun = tbabsen.getValueAt(row, 10).toString();

            String sql = "DELETE FROM tbabsen where tahun='"+tahun+"'";
            String resetno="ALTER TABLE tbabsen DROP `kode`;";
            String consecutivenumber="ALTER TABLE tbabsen ADD `kode` INT(11) NOT NULL AUTO_INCREMENT FIRST ,ADD KEY(`kode`);";

            if (JOptionPane.showConfirmDialog(null, "HAPUS DATA INI..??"
                ,"KONFIRMASI",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE)== JOptionPane.OK_OPTION) {

            try {
                conn.createStatement().execute(sql);
                conn.createStatement().execute(resetno);
                conn.createStatement().execute(consecutivenumber);

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                loadTblAbsen();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Klik Salah Satu Tabel");
        }
        }
    }//GEN-LAST:event_btnAbsen_hapus2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsen_hapus;
    private javax.swing.JButton btnAbsen_hapus1;
    private javax.swing.JButton btnAbsen_hapus2;
    private javax.swing.JButton btnAbsen_simpan;
    private javax.swing.JButton btnAbsen_tambah1;
    private javax.swing.JButton btnAbsen_ubah;
    private javax.swing.JTextField cbthn;
    private javax.swing.JLabel img_foto_absen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jdtglmulai;
    private com.toedter.calendar.JDateChooser jdtglselesai;
    private javax.swing.JLabel lbjabatanguru;
    private javax.swing.JLabel lblnamaguru;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JTextField lbtotalhari;
    private javax.swing.JPanel p_izin;
    private javax.swing.JTable tbabsen;
    private javax.swing.JTextField txtaketerangan;
    private javax.swing.JTextField txtanip;
    private com.toedter.calendar.JDateChooser txtatanggal;
    private javax.swing.JTextField txtcariabsenguru;
    private javax.swing.JLabel txtidadm7;
    private javax.swing.JTextField txtkode;
    private javax.swing.JLabel txtnamaadm7;
    // End of variables declaration//GEN-END:variables
public void absentengah(){
    headerabsen();
           DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(SwingConstants.CENTER);
             tbabsen.getColumnModel().getColumn(0).setCellRenderer(center);
             //tbabsen.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(center);
              tbabsen.getColumnModel().getColumn(1).setCellRenderer(center);
              
         tbabsen.getColumnModel().getColumn(2).setCellRenderer(center);
        // tbabsen.getTableHeader().getColumnModel().getColumn(2).setHeaderRenderer(center);
        tbabsen.getColumnModel().getColumn(3).setCellRenderer(center);
      //  tbabsen.getTableHeader().getColumnModel().getColumn(3).setHeaderRenderer(center);
        tbabsen.getColumnModel().getColumn(4).setCellRenderer(center);
      //  tbabsen.getTableHeader().getColumnModel().getColumn(4).setHeaderRenderer(center);
        tbabsen.getColumnModel().getColumn(5).setCellRenderer(center);
       // tbabsen.getTableHeader().getColumnModel().getColumn(5).setHeaderRenderer(center);
        tbabsen.getColumnModel().getColumn(6).setCellRenderer(center);
       // tbabsen.getTableHeader().getColumnModel().getColumn(6).setHeaderRenderer(center);
         tbabsen.getColumnModel().getColumn(7).setCellRenderer(center);
       //  tbabsen.getTableHeader().getColumnModel().getColumn(7).setHeaderRenderer(center);
          tbabsen.getColumnModel().getColumn(8).setCellRenderer(center);
       //  tbabsen.getTableHeader().getColumnModel().getColumn(7).setHeaderRenderer(center);
           tbabsen.getColumnModel().getColumn(9).setCellRenderer(center);
       //  tbabsen.getTableHeader().getColumnModel().getColumn(7).setHeaderRenderer(center);
            tbabsen.getColumnModel().getColumn(10).setCellRenderer(center);
       //  tbabsen.getTableHeader().getColumnModel().getColumn(7).setHeaderRenderer(center);
//      tbabsen.getColumnModel().getColumn(11).setCellRenderer(center);
//       //  tbabsen.getTableHeader().getColumnModel().getColumn(7).setHeaderRenderer(center);
     }

     public void headerabsen(){
          Font font = new Font("Times New Roman", Font.BOLD, 12);
           JTableHeader header =  tbabsen.getTableHeader();
         header.setFont(font); 
         header.setBackground(Color.CYAN);
      }
     
      protected void nama(){
           
        try {
            String sql = "SELECT * FROM admin WHERE id_admin='"+txtidadm7.getText()+"' AND  nama_admin='"+txtnamaadm7.getText()+"'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) {
               txtidadm7.setText(hasil.getString("id_admin"));
              
               txtnamaadm7.setText(hasil.getString("nama_admin"));
            }
           } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Di Panggil"+e);
        }
       }
      
      private void toExcel(JTable table, File file) {
        
        try {
            TableModel model = tbabsen.getModel();
            FileWriter excel = new FileWriter(file);
            for (int i = 0; i < model.getColumnCount(); i++) {
                excel.write(model.getColumnName(i)+"\t");
                
            }
            excel.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excel.write(model.getValueAt(i, j).toString()+"\t");
                    
                }
                excel.write("\n");
            }
            excel.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }
}
