/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import SessionLogin.UserID;
import controller.KoneksiDB;
import controller.ManajemenAdmin;
import java.awt.Color;
import java.awt.Font;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelAdmin;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAdmin
     */
    private Connection conn = new KoneksiDB().getKoneksi();
    
      DefaultTableModel tabeladmin;
        public void loadTblAdmin() throws SQLException{
        ManajemenAdmin matl = new ManajemenAdmin();
        matl.loadDataAdmin(tabeladmin);
    }
        
        
    public FormAdmin() throws SQLException {
        initComponents();
        
       String KD = UserID.getUserLogin();
        lb_id_admin.setText(KD);
        
    tabeladmin = new DefaultTableModel();
        //menambahkan TableModel ke Tabel
        tbadmin.setModel(tabeladmin);
        tabeladmin.addColumn("ID ADMIN");
        tabeladmin.addColumn("NAMA ADMIN");
        tabeladmin.addColumn("USERNAME");
        tabeladmin.addColumn("PASSWORD");
        admintengah();
        headeradmin();
        txtidadm.setEnabled(false);
        txtnamaadmin.setEnabled(false);
        txtusername.setEnabled(false);
        txtpass.setEnabled(false);
        
          loadTblAdmin();
      
    }
    
       public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = KoneksiDB.getKoneksi();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
           JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
           JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
       
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_admin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        txtidadm = new javax.swing.JTextField();
        txtnamaadmin = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        bsimpanadm = new javax.swing.JButton();
        bupdateadm = new javax.swing.JButton();
        bdeleteadm = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        tbadmin1 = new javax.swing.JScrollPane();
        tbadmin = new javax.swing.JTable();
        baru1 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lb_id_admin = new javax.swing.JTextField();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customers.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel84.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel84.setText("NAMA ADMIN");
        jPanel2.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel85.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel85.setText("PASSWORD");
        jPanel2.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtidadm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidadm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtidadm.setOpaque(false);
        txtidadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidadmActionPerformed(evt);
            }
        });
        jPanel2.add(txtidadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 30));

        txtnamaadmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnamaadmin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnamaadmin.setOpaque(false);
        jPanel2.add(txtnamaadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 320, 30));

        txtusername.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtusername.setOpaque(false);
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 320, 30));

        txtpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtpass.setOpaque(false);
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 320, 30));

        bsimpanadm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bsimpanadm.setForeground(new java.awt.Color(255, 0, 0));
        bsimpanadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-save-25.png"))); // NOI18N
        bsimpanadm.setText("Simpan");
        bsimpanadm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsimpanadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanadmActionPerformed(evt);
            }
        });
        jPanel2.add(bsimpanadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 110, 30));

        bupdateadm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bupdateadm.setForeground(new java.awt.Color(255, 0, 0));
        bupdateadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-file-25.png"))); // NOI18N
        bupdateadm.setText("Ubah");
        bupdateadm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bupdateadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateadmActionPerformed(evt);
            }
        });
        jPanel2.add(bupdateadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 100, 30));

        bdeleteadm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bdeleteadm.setForeground(new java.awt.Color(255, 0, 0));
        bdeleteadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-trash-25.png"))); // NOI18N
        bdeleteadm.setText("Hapus");
        bdeleteadm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdeleteadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteadmActionPerformed(evt);
            }
        });
        jPanel2.add(bdeleteadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 30));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 0, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancel-25.png"))); // NOI18N
        jButton11.setText("Batal");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 30));

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 0, 0));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customers.png"))); // NOI18N
        jButton12.setText("Detail Admin");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 150, 30));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel86.setText("DATA ADMIN");
        jPanel2.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        tbadmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbadmin.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbadmin.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbadminMouseClicked(evt);
            }
        });
        tbadmin1.setViewportView(tbadmin);

        jPanel2.add(tbadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 550, 90));

        baru1.setBackground(new java.awt.Color(255, 255, 255));
        baru1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        baru1.setForeground(new java.awt.Color(255, 0, 0));
        baru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-25.png"))); // NOI18N
        baru1.setText("Tambah");
        baru1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baru1ActionPerformed(evt);
            }
        });
        jPanel2.add(baru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, 30));

        jLabel94.setBackground(new java.awt.Color(255, 255, 255));
        jLabel94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel94.setOpaque(true);
        jPanel2.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, 220));

        jLabel49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 570, 160));

        lb_id_admin.setText("jTextField1");
        lb_id_admin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lb_id_adminFocusGained(evt);
            }
        });
        jPanel2.add(lb_id_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 10, 120, -1));

        javax.swing.GroupLayout p_adminLayout = new javax.swing.GroupLayout(p_admin);
        p_admin.setLayout(p_adminLayout);
        p_adminLayout.setHorizontalGroup(
            p_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_adminLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_adminLayout.setVerticalGroup(
            p_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidadmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidadmActionPerformed

    private void bsimpanadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanadmActionPerformed
        // TODO add your handling code here:
        String id_admin = txtidadm.getText();
        String nama_admin = txtnamaadmin.getText();

        String username = txtusername.getText();
        String password =  txtpass.getText();

        if( "".equals(nama_admin) | "".equals(username) |"".equals(password) ){
            JOptionPane.showMessageDialog(null, "Harap isi semua field");
        }else{

            int confirmSimpan = JOptionPane.showConfirmDialog(null,"Apakah anda data tersebut sudah benar?","Mengimput data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){

                ModelAdmin moda = new ModelAdmin();
                moda.setId_admin(id_admin);
                moda.setNama_admin(nama_admin);
                moda.setUsername(username);
                moda.setPassword(password);

                try{
                    ManajemenAdmin mana = new ManajemenAdmin();
                    // if(mana.cekGuru(moda) == true){

                        if(mana.cekDuplikasiAdmin(moda) == true){
                            int ubahData = JOptionPane.showConfirmDialog(this,
                                "Data tersebut sudah ada di database. \n"
                                + "apakah anda yakin mau merubahnya?", "Ubah data absen",
                                JOptionPane.YES_NO_CANCEL_OPTION);
                            if(ubahData == JOptionPane.YES_OPTION){
                                try{

                                    moda.setId_admin(txtidadm.getText());
                                    mana.ubahAdmin(moda);
                                    JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Data berhasil diubah",JOptionPane.INFORMATION_MESSAGE);
                                }catch(SQLException ex){
                                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan mengubah data","Kesalahan Mengubah data",JOptionPane.ERROR_MESSAGE);
                                    Logger.getLogger(FormAdmin.class.getName()).log(Level.SEVERE, null, ex);
                                }finally{
                                    loadTblAdmin();
                                }
                            }else if(ubahData == JOptionPane.NO_OPTION){

                                txtidadm.setEnabled(false);
                                txtnamaadmin.setEnabled(false);
                                txtusername.setEnabled(false);
                                txtpass.setEnabled(false);
                            }
                        }else{
                            try{
                                mana.tambahAdmin(moda);
                                JOptionPane.showMessageDialog(null, "Data berhasil ditambah", "Data berhasil ditambah",JOptionPane.INFORMATION_MESSAGE);
                            }catch(SQLException ex){
                                JOptionPane.showMessageDialog(null, "Terjadi kesalahan menambahkan data","Kesalahan Menambah Data",JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(FormAdmin.class.getName()).log(Level.SEVERE, null, ex);
                            }finally{
                                loadTblAdmin();

                                txtidadm.setText("");

                                txtnamaadmin.setEnabled(false);
                                txtnamaadmin.setText("");
                                txtnamaadmin.requestFocus();

                                txtusername.setEnabled(false);
                                txtusername.setText("");

                                txtpass.setEnabled(false);
                                txtpass.setText("");
                            }
                        }

                    }catch(SQLException ex){
                        Logger.getLogger(FormAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_bsimpanadmActionPerformed

    private void bupdateadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateadmActionPerformed
        // TODO add your handling code here:
        int i = tbadmin.getSelectedRow();
        if(i== -1 | "".equals(txtidadm.getText())){
            JOptionPane.showMessageDialog(null, "Tidak ada data admin yang dipilih");

            txtidadm.setText("");
        }
        txtnamaadmin.setEnabled(true);

        txtusername.setEnabled(true);

        txtpass.setEnabled(true);
    }//GEN-LAST:event_bupdateadmActionPerformed

    private void bdeleteadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteadmActionPerformed
        // TODO add your handling code here:
        int i = tbadmin.getSelectedRow();
        if(i== -1){
            return;
        }

        // int no = Integer.parseInt(txtkode.getText());
        ModelAdmin moda = new ModelAdmin();
        moda.setId_admin(txtidadm.getText());

        int konfirmasiHapus = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan menghapus data admin tersebut?", "Hapus Pegawai", JOptionPane.YES_NO_OPTION);
        if(konfirmasiHapus == JOptionPane.YES_OPTION){
            try{
                ManajemenAdmin mana = new ManajemenAdmin();
                mana.hapusAdmin(moda);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Berhasil Menghapus Data",JOptionPane.INFORMATION_MESSAGE);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan menghapus data","Kesalahan Menghapus Data",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FormAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try {
                    loadTblAdmin();

                    txtidadm.setText("");
                    txtnamaadmin.setEnabled(false);
                    txtnamaadmin.setText("");
                    txtusername.setEnabled(false);
                    txtusername.setText("");
                    txtpass.setEnabled(false);
                    txtpass.setText("");

                } catch (SQLException ex) {
                    Logger.getLogger(FormAdmin
                        .class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bdeleteadmActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        txtidadm.setText("");
        txtnamaadmin.setText("");
        txtusername.setText("");
        txtpass.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void tbadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbadminMouseClicked
        // TODO add your handling code here:
        txtidadm.setEnabled(false);
        txtnamaadmin.setEnabled(false);
        txtusername.setEnabled(false);
        txtpass.setEnabled(false);

        //cek apakah salah satu baris sudah diklik
        int i = tbadmin.getSelectedRow();
        if(i== -1){
            //tidak melakukan apa-apa
            return;
        }
        /*
        mengambil isi dari tabel yang di klik, lalu menampilkannya
        * di field-field
        */
        String Id_admin = (tabeladmin.getValueAt(i, 0)).toString();
        txtidadm.setText(Id_admin);

        String Nama_admin = (tabeladmin.getValueAt(i, 1)).toString();
        txtnamaadmin.setText(Nama_admin);

        String Username = (tabeladmin.getValueAt(i, 2)).toString();
        txtusername.setText(Username);

        String Password = (tabeladmin.getValueAt(i, 3)).toString();
        txtpass.setText(Password);
    }//GEN-LAST:event_tbadminMouseClicked

    private void baru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baru1ActionPerformed
        // TODO add your handling code here:
        txtidadm.setText("");
        txtidadm.setEnabled(true);
        txtidadm.setText("");
        txtidadm.requestFocus();

        txtnamaadmin.setText("");
        txtnamaadmin.setEnabled(true);
        txtnamaadmin.setText("");

        txtusername.setText("");
        txtusername.setEnabled(true);
        txtusername.setText("");

        txtpass.setText("");
        txtpass.setEnabled(true);
        txtpass.setText("");
    }//GEN-LAST:event_baru1ActionPerformed

    private void lb_id_adminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_id_adminFocusGained
        // TODO add your handling code here:
         TableRowSorter<TableModel>sorter= new TableRowSorter<TableModel>(((DefaultTableModel)tbadmin.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(lb_id_admin.getText()));
        tbadmin.setRowSorter(sorter);
    }//GEN-LAST:event_lb_id_adminFocusGained

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            // TODO add your handling code here:
            DetailAdmin d = new DetailAdmin();
            d.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FormAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru1;
    private javax.swing.JButton bdeleteadm;
    private javax.swing.JButton bsimpanadm;
    private javax.swing.JButton bupdateadm;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lb_id_admin;
    private javax.swing.JPanel p_admin;
    private javax.swing.JTable tbadmin;
    private javax.swing.JScrollPane tbadmin1;
    private javax.swing.JTextField txtidadm;
    private javax.swing.JTextField txtnamaadmin;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
 public void admintengah(){
           DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(SwingConstants.CENTER);
        tbadmin.getColumnModel().getColumn(0).setCellRenderer(center);
        tbadmin.getColumnModel().getColumn(1).setCellRenderer(center);
        tbadmin.getColumnModel().getColumn(2).setCellRenderer(center);
     }
  
   public void headeradmin(){
         Font font = new Font("Times New Roman", Font.BOLD, 12);
         JTableHeader header = tbadmin.getTableHeader();
         header.setFont(font); 
         header.setBackground(Color.CYAN);
      }
   
   protected void nama(){
           
        try {
            String sql = "SELECT * FROM admin WHERE id_admin='"+lb_id_admin.getText()+"'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) {
              
               lb_id_admin.setText(hasil.getString("id_admin"));
              
              
            }
           } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Di Panggil"+e);
        }
       }


}
