/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Renderer.TableCellRenderer;
import SessionLogin.UserID;
import controller.KoneksiDB;
import controller.ManajemenAbsenSiswa;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
 import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelSiswa;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormAbsenSiswa extends javax.swing.JInternalFrame {
     public String nis_list, nama_list,kelas_list;
private Connection conn = new KoneksiDB().getKoneksi();
    
     DefaultTableModel tabelsiswa;
        public void loadTblAbsenSiswa() throws SQLException{
        ManajemenAbsenSiswa matl = new ManajemenAbsenSiswa();
        matl.loadDataAbsenSiswa(tabelsiswa);
    }
    /**
     * Creates new form FormAbsenSiswa1
     */
    public FormAbsenSiswa() throws SQLException {
        initComponents();
       
        tabelsiswa = new DefaultTableModel();
        //menambahkan TableModel ke Tabel
        tbsiswa.setModel(tabelsiswa);
         tabelsiswa.addColumn("NO");
        tabelsiswa.addColumn("NIS");
        tabelsiswa.addColumn("NAMA SISWA");
        tabelsiswa.addColumn("KELAS");
        tabelsiswa.addColumn("SAKIT");
        tabelsiswa.addColumn("IZIN");
        tabelsiswa.addColumn("ALPHA");
        tabelsiswa.addColumn("TANGGAL");
        tbsiswa.getColumnModel().getColumn(7).setCellRenderer(new TableCellRenderer());
        siswatengah();
        headersiswa();
        txtnis.setEnabled(false);
        txtnsiswa.setEnabled(false);
        jdtgl.setEnabled(false);
        cbkelas.setEnabled(false);
        txtsakit_s.setEnabled(false);
        txtizin_s.setEnabled(false);
        txtalpha_s.setEnabled(false);
        
        
          loadTblAbsenSiswa();
      
         //pemanggilan untuk memunculkan nama yang login
        String KD = UserID.getUserLogin();
        txtidadm5.setText(KD);

        String NM = UserID.getNamaLogin();
        txtnamaadm5.setText(NM);
   
    }
    public void runReportDefault(String sourcefilename, HashMap hash) {
//        Connection con = KoneksiDB.getKoneksi();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
           JasperPrint jprint = JasperFillManager.fillReport(report,hash, conn);
           JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    
      public void itemTerpilih(){
          ListSiswa1 ls = new ListSiswa1();
          ls.siswa=this;
          txtnis.setText(nis_list);   
          txtnsiswa.setText(nama_list);  
          cbkelas.addItem(kelas_list);  
         
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_izin_siswa = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txtidadm5 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txtnamaadm5 = new javax.swing.JLabel();
        txtnsiswa = new javax.swing.JTextField();
        cbkelas = new javax.swing.JComboBox<>();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        baru = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        txtnis = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jdtgl = new com.toedter.calendar.JDateChooser();
        txtsakit_s = new javax.swing.JTextField();
        txtizin_s = new javax.swing.JTextField();
        txtnorecord = new javax.swing.JTextField();
        txtalpha_s = new javax.swing.JTextField();
        jLabel131 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        txtabsensiswa = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbsiswa = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        btnAbsen_hapus3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-attendance-25.png"))); // NOI18N

        p_izin_siswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidadm5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidadm5.setForeground(new java.awt.Color(255, 255, 255));
        txtidadm5.setText("ID ADMIN");
        jPanel17.add(txtidadm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 100, 20));

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel69.setText("NAMA SISWA");
        jPanel17.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel70.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel70.setText("KELAS");
        jPanel17.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel71.setText("KATEGORI");
        jPanel17.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 40));

        txtnamaadm5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnamaadm5.setForeground(new java.awt.Color(255, 255, 255));
        txtnamaadm5.setText("Nama Admin");
        jPanel17.add(txtnamaadm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 130, 20));

        txtnsiswa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnsiswa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnsiswa.setOpaque(false);
        txtnsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnsiswaActionPerformed(evt);
            }
        });
        jPanel17.add(txtnsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 260, 30));

        cbkelas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbkelas.setBorder(null);
        cbkelas.setOpaque(false);
        jPanel17.add(cbkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, 30));

        simpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 0, 0));
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-save-25.png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel17.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, 30));

        hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 0, 0));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-trash-25.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel17.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 100, 30));

        baru.setBackground(new java.awt.Color(255, 255, 255));
        baru.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        baru.setForeground(new java.awt.Color(255, 0, 0));
        baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-25.png"))); // NOI18N
        baru.setText("Tambah");
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });
        jPanel17.add(baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel73.setText("No Record");
        jPanel17.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 30));

        txtnis.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnis.setOpaque(false);
        jPanel17.add(txtnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 260, 30));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel74.setText("SAKIT");
        jPanel17.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 40, 20));

        jLabel75.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel75.setText("IZIN");
        jPanel17.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 20));

        jLabel76.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel76.setText("ALPA");
        jPanel17.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 20));

        jdtgl.setDateFormatString("dd MMM, yyyy");
        jdtgl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jdtgl.setOpaque(false);
        jPanel17.add(jdtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, 30));

        txtsakit_s.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtsakit_s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsakit_s.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtsakit_s.setOpaque(false);
        jPanel17.add(txtsakit_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 30, 30));

        txtizin_s.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtizin_s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtizin_s.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtizin_s.setOpaque(false);
        jPanel17.add(txtizin_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 30, 30));

        txtnorecord.setEditable(false);
        txtnorecord.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnorecord.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnorecord.setOpaque(false);
        jPanel17.add(txtnorecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 260, 30));

        txtalpha_s.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtalpha_s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtalpha_s.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtalpha_s.setOpaque(false);
        jPanel17.add(txtalpha_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 30, 30));

        jLabel131.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel131.setText("NIS");
        jPanel17.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 30));

        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 0, 0));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-file-25.png"))); // NOI18N
        update.setText("Ubah");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel17.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 100, 30));

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel77.setText("FORM IZIN SISWA");
        jPanel17.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 240, -1));

        txtabsensiswa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtabsensiswa.setOpaque(false);
        txtabsensiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabsensiswaActionPerformed(evt);
            }
        });
        txtabsensiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtabsensiswaKeyReleased(evt);
            }
        });
        jPanel17.add(txtabsensiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 190, 30));

        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-more-25.png"))); // NOI18N
        jLabel72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 40, 30));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-more-25.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, 30));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Note :\nKeterangan Untuk Izin, Alpha, Sakit :\n\nIsi angka 1 jika ia izin sakit dan alpha\n\nIsi angka 0 Jika Tidak ada izin sakit dan alpha");
        jScrollPane7.setViewportView(jTextArea4);

        jPanel17.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 290, 90));

        tbsiswa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "            NIS", "       NAMA SISWA", "          KELAS", "          SAKIT", "          IZIN", "          ALPHA", "       TANGGAL"
            }
        ));
        tbsiswa.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbsiswa.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbsiswa);

        jPanel17.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 760, 110));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-microsoft-excel-25.png"))); // NOI18N
        jButton7.setText("Export ( Excel 2003 )");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 170, 30));

        btnAbsen_hapus3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_hapus3.setForeground(new java.awt.Color(255, 0, 0));
        btnAbsen_hapus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancel-25.png"))); // NOI18N
        btnAbsen_hapus3.setText("Batal");
        btnAbsen_hapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_hapus3ActionPerformed(evt);
            }
        });
        jPanel17.add(btnAbsen_hapus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 100, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jPanel17.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 10, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jPanel17.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 10, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jPanel17.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 10, -1));

        jLabel91.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel91.setText("TANGGAL");
        jPanel17.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 30));

        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 280, 40));

        jLabel93.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 780, 170));

        jLabel99.setBackground(new java.awt.Color(255, 255, 255));
        jLabel99.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel99.setOpaque(true);
        jPanel17.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 300));

        p_izin_siswa.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(p_izin_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(p_izin_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnsiswaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String no_record = txtnorecord.getText();
        String siswa_nis = txtnis.getText();
        String nama_siswa = txtnsiswa.getText();
        String siswa_kelas = cbkelas.getSelectedItem().toString();
        String siswa_sakit = txtsakit_s.getText();
        String siswa_izin = txtizin_s.getText();
        String siswa_alpha = txtalpha_s.getText();
        String admin = txtidadm5.getText();
        Date siswa_tanggal = jdtgl.getDate();
        /* if(jdtgl.getDate() != null){
            SimpleDateFormat Format = new SimpleDate
            Format("yyyy-MM-dd");
            siswa_tanggal = Format.format(jdtgl.getDate());
        }
        */

        if( "".equals(siswa_nis) | "".equals(nama_siswa) |"".equals(siswa_kelas) |jdtgl.getDate()== null ){
            JOptionPane.showMessageDialog(null, "Harap isi semua field");
        }else{

            int confirmSimpan = JOptionPane.showConfirmDialog(null,"Apakah anda data tersebut sudah benar?","Mengimput data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){

                ModelSiswa moda = new ModelSiswa();
                moda.setNo(no_record);
                moda.setNis(siswa_nis);
                moda.setNama_siswa(nama_siswa);
                moda.setKelas(siswa_kelas);
                moda.setSakit(siswa_sakit);
                moda.setIzin(siswa_izin);
                moda.setAlpha(siswa_alpha);
                moda.setTanggal(siswa_tanggal);
                moda.setId_admin(admin);
                try{

                    ManajemenAbsenSiswa mana = new ManajemenAbsenSiswa();
                    // if(mana.cekGuru(moda) == true){

                        if(mana.cekDuplikasiSiswa(moda) == true){
                            int ubahData = JOptionPane.showConfirmDialog(this,
                                "Data tersebut sudah ada di database. \n"
                                + "apakah anda yakin mau merubahnya?", "Ubah data absen",
                                JOptionPane.YES_NO_CANCEL_OPTION);
                            if(ubahData == JOptionPane.YES_OPTION){
                                try{
                                    moda.setNo(txtnorecord.getText());
                                    mana.ubahAbsenSiswa(moda);
                                    JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Data berhasil diubah",JOptionPane.INFORMATION_MESSAGE);
                                }catch(SQLException ex){
                                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan mengubah data","Kesalahan Mengubah data",JOptionPane.ERROR_MESSAGE);
                                    Logger.getLogger(FormAbsenSiswa.class.getName()).log(Level.SEVERE, null, ex);
                                }finally{
                                    loadTblAbsenSiswa();

                                }

                            }else if(ubahData == JOptionPane.NO_OPTION){
                                txtnorecord.setEnabled(false);
                                txtnsiswa.setEnabled(false);

                                cbkelas.setEnabled(false);

                                txtsakit_s.setEnabled(false);
                                txtizin_s.setEnabled(false);
                                txtalpha_s.setEnabled(false);

                                jdtgl.setEnabled(false);
                            }

                        }else{
                            try{
                                mana.tambahAbsenSiswa(moda);
                                JOptionPane.showMessageDialog(null, "Data berhasil ditambah", "Data berhasil ditambah",JOptionPane.INFORMATION_MESSAGE);
                            }catch(SQLException ex){
                                JOptionPane.showMessageDialog(null, "Terjadi kesalahan menambahkan data","Kesalahan Menambah Data",JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(FormAbsenSiswa.class.getName()).log(Level.SEVERE, null, ex);
                            }finally{
                                loadTblAbsenSiswa();
                                txtnorecord.setText("");
                                txtnis.setText("");

                                txtnsiswa.setEnabled(false);
                                txtnsiswa.setText("");
                                txtnsiswa.requestFocus();

                                jdtgl.setEnabled(false);
                                jdtgl.setDate(null);

                                txtsakit_s.setEnabled(false);
                                txtsakit_s.setText("");
                                txtizin_s.setEnabled(false);
                                txtizin_s.setText("");
                                txtalpha_s.setEnabled(false);
                                txtalpha_s.setText("");
                                cbkelas.setEnabled(false);
                                cbkelas.setSelectedItem("");
                            }
                        }

                    }catch(SQLException ex){
                        Logger.getLogger(FormAbsenSiswa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }}
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:

        int row = tbsiswa.getSelectedRow();
        if(row!= -1){
            String cell = tbsiswa.getModel().getValueAt(row, 0).toString();
            String nomer = tbsiswa.getValueAt(row, 0).toString();

            String sql = "DELETE FROM tbabsen_siswa where no_absen='"+nomer+"'";
            String resetno="ALTER TABLE tbabsen_siswa DROP `no_absen`;";
            String consecutivenumber="ALTER TABLE tbabsen_siswa ADD `no_absen` INT(11) NOT NULL AUTO_INCREMENT FIRST ,ADD KEY(`no_absen`);";
            if (JOptionPane.showConfirmDialog(null, "HAPUS DATA INI..??"
                ,"KONFIRMASI",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE)== JOptionPane.OK_OPTION) {

            try {
                conn.createStatement().execute(sql);
                conn.createStatement().execute(resetno);
                conn.createStatement().execute(consecutivenumber);

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                loadTblAbsenSiswa();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Klik Salah Satu Tabel");
        }
        }

        //gak dipake
        /* int i = tbsiswa.getSelectedRow();
        if(i== -1){
            return;
        }
        // int no = Integer.parseInt(txtkode.getText());
        ModelSiswa moda = new ModelSiswa();
        moda.setNo(txtnorecord.getText());
        int konfirmasiHapus = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin akan menghapus data absensi tersebut?", "Hapus Pegawai", JOptionPane.YES_NO_OPTION);
        if(konfirmasiHapus == JOptionPane.YES_OPTION){
            try{
                ManajemenAbsenSiswa mana = new ManajemenAbsenSiswa();
                mana.hapusSiswa(moda);
                JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus", "Berhasil Menghapus Data",JOptionPane.INFORMATION_MESSAGE);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan menghapus data","Kesalahan Menghapus Data",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try {
                    loadTblAbsenSiswa();

                    txtnis.setText("");
                    txtnsiswa.setEnabled(false);
                    txtnsiswa.setText("");

                    jdtgl.setEnabled(false);
                    jdtgl.setDate(null);

                    cbkelas.setEnabled(false);
                    cbkelas.setSelectedItem(null);

                    txtsakit_s.setEnabled(false);
                    txtsakit_s.setText("");
                    txtizin_s.setEnabled(false);
                    txtizin_s.setText("");
                    txtalpha_s.setEnabled(false);
                    txtalpha_s.setText("");

                } catch (SQLException ex) {
                    Logger.getLogger(Administrator
                        .class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }*/
    }//GEN-LAST:event_hapusActionPerformed

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
        // TODO add your handling code here:
        txtnorecord.setText("");
        txtnorecord.setEnabled(true);
        txtnorecord.setText("");
        txtnorecord.requestFocus();

        txtnis.setText("");
        txtnis.setEnabled(true);
        txtnis.setText("");
        //txtnis.requestFocus();

        txtnsiswa.setText("");
        txtnsiswa.setEnabled(true);
        txtnsiswa.setText("");

        jdtgl.setEnabled(true);
        jdtgl.setDate(null);

        cbkelas.setEnabled(true);
        cbkelas.setSelectedItem("Pilih Kelas");
        txtsakit_s.setText("");
        txtsakit_s.setEnabled(true);
        txtsakit_s.setText("");

        txtizin_s.setText("");
        txtizin_s.setEnabled(true);
        txtizin_s.setText("");

        txtalpha_s.setText("");
        txtalpha_s.setEnabled(true);
        txtalpha_s.setText("");
    }//GEN-LAST:event_baruActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int i = tbsiswa.getSelectedRow();
        if(i== -1 | "".equals(txtnorecord.getText())){
            JOptionPane.showMessageDialog(null, "Tidak ada data absen yang dipilih");

            txtnorecord.setText("");
        }
        txtnis.setEnabled(true);
        txtnsiswa.setEnabled(true);

        cbkelas.setEnabled(true);

        txtsakit_s.setEnabled(true);
        txtizin_s.setEnabled(true);
        txtalpha_s.setEnabled(true);

        jdtgl.setEnabled(true);
    }//GEN-LAST:event_updateActionPerformed

    private void txtabsensiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabsensiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabsensiswaActionPerformed

    private void txtabsensiswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtabsensiswaKeyReleased
        // TODO add your handling code here:
        TableRowSorter<TableModel>sorter= new TableRowSorter<TableModel>(((DefaultTableModel)tbsiswa.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(txtabsensiswa.getText()));
        tbsiswa.setRowSorter(sorter);
    }//GEN-LAST:event_txtabsensiswaKeyReleased

    private void tbsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsiswaMouseClicked
        // TODO add your handling code here:
        txtnorecord.setEnabled(false);
        txtnis.setEnabled(false);
        txtnsiswa.setEnabled(false);
        cbkelas.setEnabled(false);
        txtsakit_s.setEnabled(false);
        txtizin_s.setEnabled(false);
        txtalpha_s.setEnabled(false);
        jdtgl.setEnabled(false);
        //cek apakah salah satu baris sudah diklik
        int i = tbsiswa.getSelectedRow();
        if(i== -1){
            //tidak melakukan apa-apa
            return;
        }

        /*
        mengambil isi dari tabel yang di klik, lalu menampilkannya
        * di field-field
        */

        String No = (tabelsiswa.getValueAt(i, 0)).toString();
        txtnorecord.setText(No);

        String Nis = (tabelsiswa.getValueAt(i, 1)).toString();
        txtnis.setText(Nis);

        String Nama_siswa = (tabelsiswa.getValueAt(i, 2)).toString();
        txtnsiswa.setText(Nama_siswa);

        String Kelas = (tabelsiswa.getValueAt(i, 3)).toString();
        cbkelas.setSelectedItem(Kelas);

        String Sakit = (tabelsiswa.getValueAt(i, 4).toString());
        txtsakit_s.setText(Sakit);

        String Izin = (tabelsiswa.getValueAt(i, 5)).toString();
        txtizin_s.setText(Izin);

        String Alpha = (tabelsiswa.getValueAt(i, 6)).toString();
        txtalpha_s.setText(Alpha);

        Date tanggal = (Date)tabelsiswa.getValueAt(i, 7);
        jdtgl.setDate(tanggal);
    }//GEN-LAST:event_tbsiswaMouseClicked

    private void btnAbsen_hapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_hapus3ActionPerformed
        // TODO add your handling code here:
        txtnis.setText("");
        txtnis.setEnabled(true);
        txtnis.setText("");

        txtnsiswa.setText("");

        jdtgl.setDate(null);

        cbkelas.setSelectedItem("Pilih Kelas");

        txtsakit_s.setText("");

        txtizin_s.setText("");

        txtalpha_s.setText("");
    }//GEN-LAST:event_btnAbsen_hapus3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showSaveDialog(FormAbsenSiswa.this);
        if (option== JFileChooser.APPROVE_OPTION) {
            String filename = fc.getSelectedFile().getName();
            String path = fc.getSelectedFile().getParentFile().getPath();
            int len = filename.length();
            String ext="";
            String file = "";
            if (len > 4) {
                ext = filename.substring(len-4, len);

            }
            if (ext.equals(".xls")) {
                file = path + "\\" + filename+ "";

            }else{
                file = path + "\\" + filename+ ".xls";
            }
            toExcel(tbsiswa, new File(file));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        ListSiswa1 lp = new ListSiswa1();
        lp.siswa = this;
        //this.getParent().add(lp);

        lp.setVisible(true);
        lp.setResizable(false);
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private javax.swing.JButton btnAbsen_hapus3;
    private javax.swing.JComboBox<String> cbkelas;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea4;
    private com.toedter.calendar.JDateChooser jdtgl;
    private javax.swing.JPanel p_izin_siswa;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbsiswa;
    private javax.swing.JTextField txtabsensiswa;
    private javax.swing.JTextField txtalpha_s;
    private javax.swing.JLabel txtidadm5;
    private javax.swing.JTextField txtizin_s;
    private javax.swing.JLabel txtnamaadm5;
    private javax.swing.JTextField txtnis;
    private javax.swing.JTextField txtnorecord;
    private javax.swing.JTextField txtnsiswa;
    private javax.swing.JTextField txtsakit_s;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
public void siswatengah(){
           DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(SwingConstants.CENTER);
        tbsiswa.getColumnModel().getColumn(0).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(1).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(2).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(3).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(4).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(5).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(6).setCellRenderer(center);
        tbsiswa.getColumnModel().getColumn(7).setCellRenderer(center);
         
     }
  public void headersiswa(){
         Font font = new Font("Times New Roman", Font.BOLD, 12);
        JTableHeader header = tbsiswa.getTableHeader();
         header.setFont(font); 
         header.setBackground(Color.CYAN);
      }
  
   protected void nama(){
           
        try {
            String sql = "SELECT * FROM admin WHERE id_admin='"+txtidadm5.getText()+"' AND  nama_admin='"+txtnamaadm5.getText()+"'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) {
             
               txtidadm5.setText(hasil.getString("id_admin"));
              
               txtnamaadm5.setText(hasil.getString("nama_admin"));
             
            }
           } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Di Panggil"+e);
        }
       }
   
   private void toExcel(JTable table, File file) {
        
        try {
            TableModel model = tbsiswa.getModel();
            FileWriter excel = new FileWriter(file);
            for (int i = 0; i < model.getColumnCount(); i++) {
                excel.write(model.getColumnName(i)+"\t");
                
            }
            excel.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excel.write(model.getValueAt(i, j).toString()+"\t");
                    
                }
                excel.write("\n");
            }
            excel.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }
}
