
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import SessionLogin.UserID;
import controller.KoneksiDB;
import controller.ManajemenGuru;
import java.awt.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.*;
import model.ModelGuru;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormGuru extends javax.swing.JInternalFrame {
    /**
     * Creates new form FormGuru
     */
    DefaultTableModel tabelguru;
     JFileChooser jfc;
    File file;
      private Connection conn = new KoneksiDB().getKoneksi();
      public void loadTblGuru() throws SQLException{
        ManajemenGuru mptl = new ManajemenGuru();
        mptl.loadDataGuru(tabelguru, null);
      }
    public FormGuru() throws SQLException {
        initComponents();
       
      cmbJabatan.addItem("Pilih jabatan");
            
         tabelguru = new DefaultTableModel();  
        //menambahkan TableModel ke Tabel Guru
        tbguru.setModel(tabelguru);        
        tabelguru.addColumn("KODE");
        tabelguru.addColumn("NIP");
        tabelguru.addColumn("NAMA");
        tabelguru.addColumn("JABATAN");
        tabelguru.addColumn("TUGAS TAMBAHAN");
        tabelguru.addColumn("TELEPON");
        tabelguru.addColumn("FOTO");
        tabelguru.addColumn("FILE");
         gurutengah();
        headerguru();
        
        txtkodeabs.setEnabled(false);
        txtnip.setEnabled(false);
        txtnama.setEnabled(false);
        cmbJabatan.setEnabled(false);
       cbtugas.setEnabled(false);
        txttlp.setEnabled(false);
        txtfoto.setEnabled(false);
        txtfile.setEnabled(false);
       loadJabatan();
       loadTblGuru();
       
       String KD = UserID.getUserLogin();
       txtidadm6.setText(KD);
       String NM = UserID.getNamaLogin();
       txtnamaadm6.setText(NM);
      
    }
    
     public void loadJabatan() throws SQLException {
        String sql = "SELECT * FROM tbjabatan";    
        PreparedStatement pst = KoneksiDB.getKoneksi().prepareStatement(sql);
        ResultSet rs;
        rs = pst.executeQuery(sql);
        while(rs.next()){           
            cmbJabatan.addItem(rs.getString("nama_jabatan"));
        }
    }
          // buat report
    public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = KoneksiDB.getKoneksi();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
           JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
           JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_guru = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtnamaadm6 = new javax.swing.JLabel();
        txtidadm6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        img_foto = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_tambahdata = new javax.swing.JButton();
        btn_ubahdata = new javax.swing.JButton();
        btn_hapusdata = new javax.swing.JButton();
        btn_simpandata1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbJabatan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbguru = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtfoto = new javax.swing.JTextField();
        txtfile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcariguru = new javax.swing.JTextField();
        cbtugas = new javax.swing.JComboBox<>();
        jLabel87 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txttlp = new javax.swing.JTextField();
        txtkodeabs = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        btnAbsen_hapus2 = new javax.swing.JButton();
        jLabel97 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-teacher-25.png"))); // NOI18N

        p_guru.setBackground(new java.awt.Color(255, 255, 255));
        p_guru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnamaadm6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnamaadm6.setText("Muhammad Anjar");
        jPanel5.add(txtnamaadm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 130, 20));

        txtidadm6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidadm6.setText("jLabel23");
        jPanel5.add(txtidadm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 110, 20));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 23, -1, -1));

        img_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(img_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 280, 200));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("KODE ");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("NAMA");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("TUGAS");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, 30));

        btn_tambahdata.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambahdata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_tambahdata.setForeground(new java.awt.Color(255, 0, 0));
        btn_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-25.png"))); // NOI18N
        btn_tambahdata.setText("Tambah");
        btn_tambahdata.setToolTipText("Menambah Pegawai");
        btn_tambahdata.setFocusPainted(false);
        btn_tambahdata.setRequestFocusEnabled(false);
        btn_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahdataActionPerformed(evt);
            }
        });
        jPanel5.add(btn_tambahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 30));

        btn_ubahdata.setBackground(new java.awt.Color(255, 255, 255));
        btn_ubahdata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_ubahdata.setForeground(new java.awt.Color(255, 0, 0));
        btn_ubahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-file-25.png"))); // NOI18N
        btn_ubahdata.setText("Ubah");
        btn_ubahdata.setToolTipText("Mengubah data yang terseleksi");
        btn_ubahdata.setFocusPainted(false);
        btn_ubahdata.setRequestFocusEnabled(false);
        btn_ubahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahdataActionPerformed(evt);
            }
        });
        jPanel5.add(btn_ubahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 100, 29));

        btn_hapusdata.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapusdata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_hapusdata.setForeground(new java.awt.Color(255, 0, 0));
        btn_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-trash-25.png"))); // NOI18N
        btn_hapusdata.setText("Hapus");
        btn_hapusdata.setToolTipText("Menghapus data yang terseleksi");
        btn_hapusdata.setFocusPainted(false);
        btn_hapusdata.setRequestFocusEnabled(false);
        btn_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusdataActionPerformed(evt);
            }
        });
        jPanel5.add(btn_hapusdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 100, 30));

        btn_simpandata1.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpandata1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_simpandata1.setForeground(new java.awt.Color(255, 0, 0));
        btn_simpandata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-save-25.png"))); // NOI18N
        btn_simpandata1.setText("Simpan");
        btn_simpandata1.setToolTipText("Menyimpan data baru atau perubahan");
        btn_simpandata1.setFocusPainted(false);
        btn_simpandata1.setRequestFocusEnabled(false);
        btn_simpandata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpandata1MouseClicked(evt);
            }
        });
        btn_simpandata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpandata1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn_simpandata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 110, 31));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-opened-folder-25.png"))); // NOI18N
        jButton2.setText("File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 30));

        cmbJabatan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbJabatan.setOpaque(false);
        jPanel5.add(cmbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 160, 30));

        jScrollPane2.setBackground(new java.awt.Color(51, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 51, 255));

        tbguru.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbguru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "                      KODE ABSEN", "                        NIP", "	                NAMA LENGKAP", "                     JABATAN", "              TUGAS TAMBAHAN", "                     TELEPON", "                        FOTO"
            }
        ));
        tbguru.setGridColor(new java.awt.Color(0, 0, 0));
        tbguru.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbguru.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbguruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbguru);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 790, 130));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cari Data");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 70, 30));

        txtnip.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnip.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnip.setOpaque(false);
        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });
        jPanel5.add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 290, 30));

        txtnama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnama.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnama.setOpaque(false);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel5.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 290, 30));

        txtfoto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtfoto.setForeground(new java.awt.Color(255, 255, 255));
        txtfoto.setBorder(null);
        txtfoto.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtfoto.setOpaque(false);
        jPanel5.add(txtfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 90, 30));

        txtfile.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        txtfile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtfile.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfile.setOpaque(false);
        jPanel5.add(txtfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("FORM GURU");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 420, 40));

        txtcariguru.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtcariguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariguruActionPerformed(evt);
            }
        });
        txtcariguru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariguruKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcariguruKeyTyped(evt);
            }
        });
        jPanel5.add(txtcariguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 220, 30));

        cbtugas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbtugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH TUGAS TAMBAHAN --", "-", "Ka.Program AK", "Ka.Program AP", "Wabid.Kesiswaan", "Wabid.Kurikulum", "Walas X OTKP 1", "Walas X OTKP 2", "Walas X OTKP 3", "Walas XI OTKP 1", "Walas XI OTKP 2", "Walas XI OTKP 3", "Walas XII OTKP 1", "Walas XII OTKP 2", "Walas XII OTKP 3", "Walas X AKL 1", "Walas X AKL 2", "Walas X AKL 3", "Walas XI AKL 1", "Walas XI AKL 2", "Walas XI AKL 3", "Walas XII AKL 1", "Walas XII AKL 2", "Walas XII AKL 3", "Staff" }));
        cbtugas.setOpaque(false);
        jPanel5.add(cbtugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 160, 30));

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-more-25.png"))); // NOI18N
        jPanel5.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("TELEPON");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("JABATAN");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 30));

        txttlp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txttlp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txttlp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txttlp.setOpaque(false);
        txttlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttlpActionPerformed(evt);
            }
        });
        jPanel5.add(txttlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, 30));

        txtkodeabs.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtkodeabs.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtkodeabs.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtkodeabs.setOpaque(false);
        txtkodeabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeabsActionPerformed(evt);
            }
        });
        jPanel5.add(txtkodeabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 290, 30));

        jLabel95.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel95.setText("NIP");
        jPanel5.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 30));

        btnAbsen_hapus2.setBackground(new java.awt.Color(255, 255, 255));
        btnAbsen_hapus2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbsen_hapus2.setForeground(new java.awt.Color(255, 0, 0));
        btnAbsen_hapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancel-25.png"))); // NOI18N
        btnAbsen_hapus2.setText("Batal");
        btnAbsen_hapus2.setToolTipText("");
        btnAbsen_hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_hapus2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAbsen_hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 100, 30));

        jLabel97.setBackground(new java.awt.Color(255, 255, 255));
        jLabel97.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel97.setOpaque(true);
        jPanel5.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 810, 260));

        jLabel50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 810, 190));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 530));

        javax.swing.GroupLayout p_guruLayout = new javax.swing.GroupLayout(p_guru);
        p_guru.setLayout(p_guruLayout);
        p_guruLayout.setHorizontalGroup(
            p_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_guruLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_guruLayout.setVerticalGroup(
            p_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(p_guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahdataActionPerformed
        // TODO add your handling code here:
        txtkodeabs.setEnabled(true);
        txtkodeabs.setText("");
        txtkodeabs.requestFocus();

        txtnip.setEnabled(true);
        txtnip.setText("");

        txtnama.setEnabled(true);
        txtnama.setText("");
        
        txttlp.setEnabled(true);
        txttlp.setText("");
        
        cmbJabatan.setEnabled(true);
        cmbJabatan.setSelectedIndex(0);
        
        cbtugas.setEnabled(true);
        cbtugas.setSelectedIndex(0);
        txtfoto.setEnabled(true);
        txtfoto.setText("");
        txtfile.setEnabled(true);
        txtfile.setText("");
        img_foto.setIcon(null);

        //Shift.setEnabled(true);
    }//GEN-LAST:event_btn_tambahdataActionPerformed

    private void btn_ubahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahdataActionPerformed
        // TODO add your handling code here:
        int i = tbguru.getSelectedRow();
        if(i== -1){
            JOptionPane.showMessageDialog(null, "Tidak ada data guru yang dipilih");
        }
        txtkodeabs.setEnabled(false);
        txtnip.setEnabled(true);
        txtnama.setEnabled(true);
        cmbJabatan.setEnabled(true);
          txttlp.setEnabled(true);
        cbtugas.setEnabled(true);
        txtfoto.setEnabled(true);
        //Shift.setEnabled(true);
    }//GEN-LAST:event_btn_ubahdataActionPerformed

    private void btn_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusdataActionPerformed
        // TODO add your handling code here:
        int i = tbguru.getSelectedRow();
        if(i== -1){
            return;
        }
        String nip_abs = (String) tbguru.getValueAt(i, 0);
        String nip = (String) tbguru.getValueAt(i, 1);
        String nama = (String) tbguru.getValueAt(i, 2);

        ModelGuru modg = new ModelGuru();
        modg.setNip_absen(nip_abs);
        modg.setNip(nip);
        modg.setNama(nama);

        int konfirmasiHapus = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan menghapus data guru "
            + "dengan \n Kode Absen "+nip_abs+" Untuk NIP "+nip+" yang bernama "+nama+"? ", "Hapus Guru", JOptionPane.YES_NO_OPTION);
        if(konfirmasiHapus == JOptionPane.YES_OPTION){
            try{
                ManajemenGuru mang = new ManajemenGuru();
                mang.hapusGuru(modg);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Berhasil Menghapus Data",JOptionPane.INFORMATION_MESSAGE);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan menghapus data","Kesalahan Menghapus Data",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try {
                    loadTblGuru();
                    txtkodeabs.setEnabled(false);
                    txtkodeabs.setText("");

                    txtnip.setEnabled(false);
                    txtnip.setText("");

                    txtnama.setEnabled(false);
                    txtnama.setText("");

                    cmbJabatan.setEnabled(false);
                    cmbJabatan.setSelectedIndex(0);
                    
                    txttlp.setEnabled(false);
                    txttlp.setText("");

                    cbtugas.setEnabled(false);
                    cbtugas.setSelectedIndex(0);
                    
                    txtfoto.setEnabled(false);
                    txtfoto.setText("");

                } catch (SQLException ex) {
                    Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_hapusdataActionPerformed

    private void btn_simpandata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpandata1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpandata1MouseClicked

    private void btn_simpandata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpandata1ActionPerformed
        // TODO add your handling code here:

        String nip_absen_guru = txtkodeabs.getText();
        String nip_guru = txtnip.getText();
        String nama_guru = txtnama.getText();
        String jabatan_guru = "";
        String admin = txtidadm6.getText();
        switch(cmbJabatan.getSelectedIndex()){

            case 1: jabatan_guru = "KEPSEK"; break;
            case 2: jabatan_guru = "GURU"; break;
            case 3: jabatan_guru = "STAFF"; break;

            default:jabatan_guru = "";break;
        }
        String tugas = cbtugas.getSelectedItem().toString();
        String tlp = txttlp.getText();
        String foto_guru = txtfoto.getText();
        String files = txtfile.getText();
        /* String shift_guru = "";
        switch(Shift.getSelectedIndex()){
            case 0: shift_guru = "Pagi"; break;
            case 1: shift_guru = "Siang"; break;

        }*/

        //logika agar semua field terisi
        if(nip_absen_guru.equals("") |nip_guru.equals("") | nama_guru.equals("") | jabatan_guru.equals("")
        ){
            JOptionPane.showMessageDialog(null, "Harap isi semua field");
        }else{

            int confirmSimpan = JOptionPane.showConfirmDialog(null,"Apakah anda data tersebut sudah benar?","Mengimput data",JOptionPane.YES_NO_OPTION);
            if (confirmSimpan == JOptionPane.YES_OPTION){
                //panggil model, set model sesuai dgn variabel
                ModelGuru modg = new ModelGuru();
                modg.setNip_absen(nip_absen_guru);
                modg.setNip(nip_guru);
                modg.setNama(nama_guru);
                modg.setJabatan(jabatan_guru);
                modg.setTugas(tugas);
                modg.setTlp(tlp);
                modg.setFoto(foto_guru);
                modg.setFile(files);
                modg.setId_admin(admin);

                //memulai mengkoneksikan menginputkan ke database
                //memulai mengkoneksikan menginputkan ke database

                try{
                    ManajemenGuru mang = new ManajemenGuru();

                    //Cek apakah guru tersebut ada di database
                    //Jika NIP guru tersebut sudah ada di data, maka..
                    if(mang.cekGuru(modg) == true){

                        //tampilkan peringatan bahwa data sudah data, dan mau diubah?
                        int konfirmasiUbah = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan mengubah data Guru ..!  \n Kode Absen  : "+modg.getNip_absen()+" menjadi.. \n ------------------------------------------"
                            + " \n NIP       :"+modg.getNip()+"  \nNama     : "+modg.getNama()+" \nJabatan : "+modg.getJabatan()+" \nTugas Tambahan : "+modg.getTugas()+ " \nFoto        : "+modg.getFoto()+" \nYakin ubah data guru ? ",
                            "Ubah Data Guru", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
                        //jika user klik yes
                        if(konfirmasiUbah == JOptionPane.YES_OPTION){
                            //lakukan mekanisme update informasi kedatabase
                            try{
                                modg.setNip_absen(txtkodeabs.getText());
                                mang.updateGuru(modg);
                                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Data berhasil diubah",JOptionPane.INFORMATION_MESSAGE);
                            }catch(SQLException ex){
                                JOptionPane.showMessageDialog(null, "Terjadi kesalahan mengubah data","Kesalahan Mengubah data",JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
                            }finally{
                                loadTblGuru();

                            }
                        }else if(konfirmasiUbah == JOptionPane.NO_OPTION){

                            txtkodeabs.setEnabled(false);
                            txtkodeabs.setText("");

                            txtnip.setEnabled(false);
                            txtnip.setText("");

                            txtnama.setEnabled(false);
                            txtnama.setText("");

                            cmbJabatan.setEnabled(false);
                            cmbJabatan.setSelectedIndex(0);
                            
                             cbtugas.setEnabled(false);
                            cbtugas.setSelectedIndex(0);
                            
                             txttlp.setEnabled(false);
                            txttlp.setText("");

                            txtfoto.setEnabled(false);
                            txtfoto.setText("");
                            txtfile.setEnabled(false);
                            txtfile.setText("");
                            // Shift.setEnabled(false);
                            //Shift.setSelectedIndex(0);
                        }
                    }else{
                        try{
                            mang.tambahGuru(modg);
                            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan", "Berhasil Menambahkan Dambahkan",JOptionPane.INFORMATION_MESSAGE);

                        }catch(SQLException ex){
                            JOptionPane.showMessageDialog(null, "Terjadi kesalahan menambahkan data","Kesalahan Menambah Data",JOptionPane.ERROR_MESSAGE);
                            Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
                        }finally{
                            loadTblGuru();

                            txtkodeabs.setEnabled(false);
                            txtkodeabs.setText("");

                            txtnip.setEnabled(false);
                            txtnip.setText("");

                            txtnama.setEnabled(false);
                            txtnama.setText("");

                            cmbJabatan.setEnabled(false);
                            cmbJabatan.setSelectedIndex(0);
                            
                            cbtugas.setEnabled(false);
                            cbtugas.setSelectedIndex(0);
                            
                            txttlp.setEnabled(false);
                            txttlp.setText("");

                            txtfoto.setEnabled(false);
                            txtfoto.setText("");
                            txtfile.setEnabled(false);
                            txtfile.setText("");
                            // Shift.setEnabled(false);
                            // Shift.setSelectedIndex(0);
                        }
                    }

                }catch(SQLException ex){
                    Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);

                }
            }

        }
    }//GEN-LAST:event_btn_simpandata1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        jfc = new JFileChooser();
//        if(jfc.showOpenDialog(img_foto)==JFileChooser.APPROVE_OPTION){
//            Toolkit toolkit = Toolkit.getDefaultToolkit();
//            Image image = toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
//            Image imagedResized=image.getScaledInstance(300,350,Image.SCALE_DEFAULT);
//            ImageIcon imageIcon=new ImageIcon(imagedResized);
//            img_foto.setIcon(imageIcon);
//            txtfoto.setText(jfc.getSelectedFile().getName());
//            file = new File(jfc.getSelectedFile().getPath());
//        }
    String currentDirectoryPath="C:\\Users\\Anjar\\Documents\\FotoGuru";
        jfc = new JFileChooser(currentDirectoryPath);
        int imageChooser = jfc.showOpenDialog(null);
        jfc.setDialogTitle("Choose Image..");
        FileNameExtensionFilter fnef= new FileNameExtensionFilter("IMAGES", "png","jpg","jpeg");
        jfc.setFileFilter(fnef);
        
        if(imageChooser==JFileChooser.APPROVE_OPTION){
            File imageFile = jfc.getSelectedFile();
            String imageFileName = imageFile.getName();
            String imageFilePath = imageFile.getAbsolutePath();
            txtfoto.setText(imageFileName);
            ImageIcon imageIcon = new ImageIcon(imageFilePath);
           // Image image = toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image image=imageIcon.getImage().getScaledInstance(img_foto.getWidth(),img_foto.getHeight(),Image.SCALE_DEFAULT);
            ImageIcon resizedImageIcon=new ImageIcon(image);
            
            img_foto.setIcon(resizedImageIcon);
            // display image path file
            txtfile.setText(imageFilePath);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbguruMouseClicked
        // TODO add your handling code here:

        //ubah keadaan field-field menjadi tidak berfungsi
        txtkodeabs.setEnabled(false);
        txtnip.setEnabled(false);
        txtnama.setEnabled(false);
        cmbJabatan.setEnabled(false);
         txttlp.setEnabled(false);
        cbtugas.setEnabled(false);
        txtfoto.setEnabled(false);
         txtfile.setEnabled(false);
        // Shift.setEnabled(false);

        //cek apakah salah satu baris sudah diklik
        int i = tbguru.getSelectedRow();
        if(i== -1){
            //tidak melakukan apa-apa
            return;
        }

        /*
        mengambil isi dari tabel yang di klik, lalu menampilkannya
        * di field-field
        */
        String nip_abs = (String) tbguru.getValueAt(i, 0);
        txtkodeabs.setText(nip_abs);

        String nip = (String) tbguru.getValueAt(i, 1);
        txtnip.setText(nip);

        String nama = (String) tbguru.getValueAt(i, 2);
        txtnama.setText(nama);

        Object jabatan = (Object) tbguru.getValueAt(i, 3);
        cmbJabatan.setSelectedItem(jabatan);
        
          String tugas = (String) tbguru.getValueAt(i, 4);
        cbtugas.setSelectedItem(tugas);
        
        String tlp = (String) tbguru.getValueAt(i, 5);
        txttlp.setText(tlp);
        
        String foto= (String)tbguru.getValueAt(i,6);
        txtfoto.setText(foto);
        
         String files= (String)tbguru.getValueAt(i,7);
        txtfile.setText(files);
        img_foto.setIcon(new ImageIcon(new ImageIcon(files).getImage().getScaledInstance(img_foto.getWidth(), img_foto.getHeight(), Image.SCALE_SMOOTH)));//("D:/PICT/"+foto)));
       //"C:/Users/Anjar/Documents/FotoGuru/"+foto
        
//Object shift = (Object) tbguru.getValueAt(i, 5);
        //Shift.setSelectedItem(shift);
    }//GEN-LAST:event_tbguruMouseClicked

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtcariguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariguruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariguruActionPerformed

    private void txtcariguruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariguruKeyReleased
        // TODO add your handling code here:
        TableRowSorter<TableModel>sorter= new TableRowSorter<TableModel>(((DefaultTableModel)tbguru.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(txtcariguru.getText()));
        tbguru.setRowSorter(sorter);
    }//GEN-LAST:event_txtcariguruKeyReleased

    private void txtcariguruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariguruKeyTyped
        // TODO add your handling code here
    }//GEN-LAST:event_txtcariguruKeyTyped

    private void txtkodeabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeabsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeabsActionPerformed

    private void btnAbsen_hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_hapus2ActionPerformed
        // TODO add your handling code here:
        txtkodeabs.setText("");
        txtnip.setText("");
        txtnama.setText("");
        cmbJabatan.setSelectedIndex(0);
          txttlp.setText("");
        cbtugas.setSelectedIndex(0);
        txtfoto.setText("");
         txtfile.setText("");
        //  cbshift.setSelectedItem("");
    }//GEN-LAST:event_btnAbsen_hapus2ActionPerformed

    private void txttlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttlpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsen_hapus2;
    private javax.swing.JButton btn_hapusdata;
    private javax.swing.JButton btn_simpandata1;
    private javax.swing.JButton btn_tambahdata;
    private javax.swing.JButton btn_ubahdata;
    private javax.swing.JComboBox<String> cbtugas;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JLabel img_foto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_guru;
    private javax.swing.JTable tbguru;
    private javax.swing.JTextField txtcariguru;
    private javax.swing.JTextField txtfile;
    private javax.swing.JTextField txtfoto;
    private javax.swing.JLabel txtidadm6;
    private javax.swing.JTextField txtkodeabs;
    private javax.swing.JTextField txtnama;
    private javax.swing.JLabel txtnamaadm6;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txttlp;
    // End of variables declaration//GEN-END:variables
protected void nama(){
           
        try {
            String sql = "SELECT * FROM admin WHERE id_admin='"+txtidadm6.getText()+"' AND  nama_admin='"+txtnamaadm6.getText()+"'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) {
              
               txtidadm6.setText(hasil.getString("id_admin"));
               
               txtnamaadm6.setText(hasil.getString("nama_admin"));
               
            }
           } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Di Panggil"+e);
        }
        
       }
 

 public void gurutengah(){
          DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(SwingConstants.CENTER);
        tbguru.getColumnModel().getColumn(0).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(1).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(2).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(3).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(4).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(5).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(6).setCellRenderer(center);
        tbguru.getColumnModel().getColumn(7).setCellRenderer(center);
        
     }

 public void headerguru(){
          Font font = new Font("Times New Roman", Font.BOLD, 12);
         JTableHeader header = tbguru.getTableHeader();
         header.setFont(font); 
         header.setBackground(Color.CYAN);
      }

}
