/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import SessionLogin.UserID;
import controller.KoneksiDB;
import controller.ManajemenAdmin;
import controller.ManajemenKelas;
import java.awt.Color;
import java.awt.Font;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelAdmin;
import model.ModelKelas;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormKelas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAdmin
     */
    private Connection conn = new KoneksiDB().getKoneksi();
    
      DefaultTableModel tabelkelas;
        public void loadTblKelas() throws SQLException{
        ManajemenKelas matl = new ManajemenKelas();
        matl.loadDataKelas(tabelkelas);
    }
        
        
    public FormKelas() throws SQLException {
        initComponents();
        
        
       tabelkelas = new DefaultTableModel();
        //menambahkan TableModel ke Tabel
        tbkelas.setModel(tabelkelas);
        tabelkelas.addColumn("NO");
        tabelkelas.addColumn("NAMA KELAS");
        
        admintengah();
        headeradmin();
        txtno.setEnabled(false);
        txtnamakelas.setEnabled(false);
     
        
          loadTblKelas();
      
    }
    
   
       
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_admin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        txtnamakelas = new javax.swing.JTextField();
        bsimpanadm = new javax.swing.JButton();
        bupdateadm = new javax.swing.JButton();
        bdeleteadm = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbadmin1 = new javax.swing.JScrollPane();
        tbkelas = new javax.swing.JTable();
        baru1 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customers.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("*NO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("NAMA KELAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        txtno.setEditable(false);
        txtno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtno.setOpaque(false);
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, 30));

        txtnamakelas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnamakelas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtnamakelas.setOpaque(false);
        txtnamakelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamakelasActionPerformed(evt);
            }
        });
        jPanel2.add(txtnamakelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, 30));

        bsimpanadm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bsimpanadm.setForeground(new java.awt.Color(255, 0, 0));
        bsimpanadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-save-25.png"))); // NOI18N
        bsimpanadm.setText("Simpan");
        bsimpanadm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsimpanadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanadmActionPerformed(evt);
            }
        });
        jPanel2.add(bsimpanadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 110, 30));

        bupdateadm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bupdateadm.setForeground(new java.awt.Color(255, 0, 0));
        bupdateadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-file-25.png"))); // NOI18N
        bupdateadm.setText("Ubah");
        bupdateadm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bupdateadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateadmActionPerformed(evt);
            }
        });
        jPanel2.add(bupdateadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 100, 30));

        bdeleteadm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bdeleteadm.setForeground(new java.awt.Color(255, 0, 0));
        bdeleteadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-trash-25.png"))); // NOI18N
        bdeleteadm.setText("Hapus");
        bdeleteadm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdeleteadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteadmActionPerformed(evt);
            }
        });
        jPanel2.add(bdeleteadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 30));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 0, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancel-25.png"))); // NOI18N
        jButton11.setText("Batal");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 30));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel86.setText("DATA KELAS");
        jPanel2.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel3.setText("* kosongkan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        tbkelas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbkelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbkelas.setSelectionBackground(new java.awt.Color(0, 204, 0));
        tbkelas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbkelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbkelasMouseClicked(evt);
            }
        });
        tbadmin1.setViewportView(tbkelas);

        jPanel2.add(tbadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 550, 130));

        baru1.setBackground(new java.awt.Color(255, 255, 255));
        baru1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        baru1.setForeground(new java.awt.Color(255, 0, 0));
        baru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-25.png"))); // NOI18N
        baru1.setText("Tambah");
        baru1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baru1ActionPerformed(evt);
            }
        });
        jPanel2.add(baru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, 30));

        jLabel94.setBackground(new java.awt.Color(255, 255, 255));
        jLabel94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel94.setOpaque(true);
        jPanel2.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, 220));

        jLabel49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 570, 160));

        javax.swing.GroupLayout p_adminLayout = new javax.swing.GroupLayout(p_admin);
        p_admin.setLayout(p_adminLayout);
        p_adminLayout.setHorizontalGroup(
            p_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_adminLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_adminLayout.setVerticalGroup(
            p_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void bsimpanadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanadmActionPerformed
        // TODO add your handling code here:
        String kode = txtno.getText();

        String nama_kelas = txtnamakelas.getText();


        if( "".equals(nama_kelas) ){
            JOptionPane.showMessageDialog(null, "Harap isi semua field");
        }else{

            int confirmSimpan = JOptionPane.showConfirmDialog(null,"Apakah anda data tersebut sudah benar?","Mengimput data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){

                ModelKelas moda = new ModelKelas();
                moda.setKode(kode);
           
                moda.setNama_kelas(nama_kelas);
        
                try{
                    ManajemenKelas mana = new ManajemenKelas();
                    // if(mana.cekGuru(moda) == true){

                        if(mana.cekDuplikasi(moda) == true){
                            int ubahData = JOptionPane.showConfirmDialog(this,
                                "Data tersebut sudah ada di database. \n"
                                + "apakah anda yakin mau merubahnya?", "Ubah data absen",
                                JOptionPane.YES_NO_CANCEL_OPTION);
                            if(ubahData == JOptionPane.YES_OPTION){
                                try{

                                    moda.setKode(txtno.getText());
                                    mana.ubahKelas(moda);
                                    JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Data berhasil diubah",JOptionPane.INFORMATION_MESSAGE);
                                }catch(SQLException ex){
                                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan mengubah data","Kesalahan Mengubah data",JOptionPane.ERROR_MESSAGE);
                                    Logger.getLogger(FormKelas.class.getName()).log(Level.SEVERE, null, ex);
                                }finally{
                                    loadTblKelas();
                                }
                            }else if(ubahData == JOptionPane.NO_OPTION){

                                txtno.setEnabled(false);
                          
                                txtnamakelas.setEnabled(false);
                             
                            }
                        }else{
                            try{
                                mana.tambahKelas(moda);
                                JOptionPane.showMessageDialog(null, "Data berhasil ditambah", "Data berhasil ditambah",JOptionPane.INFORMATION_MESSAGE);
                            }catch(SQLException ex){
                                JOptionPane.showMessageDialog(null, "Terjadi kesalahan menambahkan data","Kesalahan Menambah Data",JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(FormKelas.class.getName()).log(Level.SEVERE, null, ex);
                            }finally{
                                loadTblKelas();

                                txtno.setText("");

                                txtnamakelas.setEnabled(false);
                                txtnamakelas.setText("");
                                txtnamakelas.requestFocus();


                            
                            }
                        }

                    }catch(SQLException ex){
                        Logger.getLogger(FormKelas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_bsimpanadmActionPerformed

    private void bupdateadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateadmActionPerformed
        // TODO add your handling code here:
        int i = tbkelas.getSelectedRow();
        if(i== -1 | "".equals(txtno.getText())){
            JOptionPane.showMessageDialog(null, "Tidak ada data admin yang dipilih");

            txtno.setText("");
        }

        txtnamakelas.setEnabled(true);

    }//GEN-LAST:event_bupdateadmActionPerformed

    private void bdeleteadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteadmActionPerformed
        // TODO add your handling code here:
         int row = tbkelas.getSelectedRow();
        if(row!= -1){
            String cell = tbkelas.getModel().getValueAt(row, 0).toString();
            String nomer = tbkelas.getValueAt(row, 0).toString();

            String sql = "DELETE FROM tbkelas where kode='"+nomer+"'";
            String resetno="ALTER TABLE tbkelas DROP `kode`;";
            String consecutivenumber="ALTER TABLE tbkelas ADD `kode` INT(11) NOT NULL AUTO_INCREMENT FIRST ,ADD KEY(`kode`);";

            if (JOptionPane.showConfirmDialog(null, "HAPUS DATA INI..??"
                ,"KONFIRMASI",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE)== JOptionPane.OK_OPTION) {

            try {
                conn.createStatement().execute(sql);
                conn.createStatement().execute(resetno);
                conn.createStatement().execute(consecutivenumber);

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                loadTblKelas();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Klik Salah Satu Tabel");
        }
        }
        
    }//GEN-LAST:event_bdeleteadmActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        txtno.setText("");
        txtnamakelas.setText("");
      
    }//GEN-LAST:event_jButton11ActionPerformed

    private void tbkelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbkelasMouseClicked
        // TODO add your handling code here:
        txtno.setEnabled(false);
        txtnamakelas.setEnabled(false);
      

        //cek apakah salah satu baris sudah diklik
        int i = tbkelas.getSelectedRow();
        if(i== -1){
            //tidak melakukan apa-apa
            return;
        }
        /*
        mengambil isi dari tabel yang di klik, lalu menampilkannya
        * di field-field
        */
        String Kode = (tabelkelas.getValueAt(i, 0)).toString();
        txtno.setText(Kode);

        String Nama_kelas = (tabelkelas.getValueAt(i, 1)).toString();
        txtnamakelas.setText(Nama_kelas);

    }//GEN-LAST:event_tbkelasMouseClicked

    private void baru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baru1ActionPerformed
        // TODO add your handling code here:
        txtno.setText("");
        txtno.setEnabled(true);
        txtno.setText("");
        txtnamakelas.setText("");
        txtnamakelas.setEnabled(true);
        txtnamakelas.setText("");
        txtnamakelas.requestFocus();

    }//GEN-LAST:event_baru1ActionPerformed

    private void txtnamakelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamakelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamakelasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru1;
    private javax.swing.JButton bdeleteadm;
    private javax.swing.JButton bsimpanadm;
    private javax.swing.JButton bupdateadm;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel p_admin;
    private javax.swing.JScrollPane tbadmin1;
    private javax.swing.JTable tbkelas;
    private javax.swing.JTextField txtnamakelas;
    private javax.swing.JTextField txtno;
    // End of variables declaration//GEN-END:variables
 public void admintengah(){
           DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(SwingConstants.CENTER);
        tbkelas.getColumnModel().getColumn(0).setCellRenderer(center);
        tbkelas.getColumnModel().getColumn(1).setCellRenderer(center);
     
     }
  
   public void headeradmin(){
         Font font = new Font("Times New Roman", Font.BOLD, 12);
         JTableHeader header = tbkelas.getTableHeader();
         header.setFont(font); 
         header.setBackground(Color.CYAN);
      }
   
}
